// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 16:06:23

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class CustomersController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public CustomersController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Customer>();
        var items = objectSpace.GetObjectsQuery<Customer>()
            .Select(e => new
            {
                e.Oid,
                e.Code,
                e.Name,
                e.Email,
                e.Phone,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Customer>();
        var item = objectSpace.GetObjectByKey<Customer>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.Code,
            item.Name,
            item.Email,
            item.Phone,
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] CustomerDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Customer>();
        var item = objectSpace.CreateObject<Customer>();
        item.Code = dto.Code;
        item.Name = dto.Name;
        item.Email = dto.Email;
        item.Phone = dto.Phone;

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] CustomerDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Customer>();
        var item = objectSpace.GetObjectByKey<Customer>(id);
        if (item == null) return NotFound();
        item.Code = dto.Code;
        item.Name = dto.Name;
        item.Email = dto.Email;
        item.Phone = dto.Phone;

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Customer>();
        var item = objectSpace.GetObjectByKey<Customer>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for Customer Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class CustomerDto
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
}

