// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 16:14:21

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class OrdersController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public OrdersController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var items = objectSpace.GetObjectsQuery<Order>()
            .Select(e => new
            {
                e.Oid,
                e.OrderNo,
                e.OrderDate,
                e.TotalAmount,
                customerId = e.Customer != null ? e.Customer.Oid : (Guid?)null,
                CustomerName = e.Customer != null ? e.Customer.Name : null,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.GetObjectByKey<Order>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.OrderNo,
            item.OrderDate,
            item.TotalAmount,
            customerId = item.Customer?.Oid,
            customerName = item.Customer?.Name,
        });
    }

    /// <summary>
    /// Get entity with full details including relations.
    /// </summary>
    [HttpGet("{id}/details")]
    public IActionResult GetDetails(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.GetObjectByKey<Order>(id);
        if (item == null) return NotFound();

        return Ok(new OrderDetailsDto
        {
            Oid = item.Oid,
            OrderNo = item.OrderNo,
            OrderDate = item.OrderDate,
            TotalAmount = item.TotalAmount,
            Customer = item.Customer != null ? new OrderCustomerRefDto
            {
                Oid = item.Customer.Oid,
                Name = item.Customer.Name ?? string.Empty,
            } : null,
            Items = item.Items?.Select(d => new OrderOrderItemItemDto
            {
                Oid = d.Oid,
                Quantity = d.Quantity,
                Price = d.Price,
                LineTotal = d.LineTotal,
                ProductId = d.Product?.Oid ?? Guid.Empty,
                productName = d.Product?.Name,
            }).ToList() ?? new(),
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] OrderDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.CreateObject<Order>();
        item.OrderNo = dto.OrderNo;
        item.OrderDate = dto.OrderDate ?? DateTime.Today;

        // Set Customer reference
        if (dto.customerId.HasValue)
        {
            item.Customer = objectSpace.GetObjectByKey<Customer>(dto.customerId.Value);
        }

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] OrderDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.GetObjectByKey<Order>(id);
        if (item == null) return NotFound();
        item.OrderNo = dto.OrderNo;
        item.OrderDate = dto.OrderDate ?? DateTime.Today;

        // Update Customer reference
        if (dto.customerId.HasValue)
        {
            item.Customer = objectSpace.GetObjectByKey<Customer>(dto.customerId.Value);
        }
        else
        {
            item.Customer = null;
        }

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.GetObjectByKey<Order>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

    // ============ Items Detail Endpoints ============

    /// <summary>
    /// Get all Items items for this entity.
    /// </summary>
    [HttpGet("{id}/items")]
    public IActionResult GetItems(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var item = objectSpace.GetObjectByKey<Order>(id);
        if (item == null) return NotFound();

        var items = item.Items?.Select(d => new { d.Oid, d.Quantity, d.Price, d.LineTotal, ProductId = d.Product?.Oid ?? Guid.Empty, productName = d.Product?.Name }).ToList() ?? new();
        return Ok(items);
    }

    /// <summary>
    /// Add a new Items item.
    /// </summary>
    [HttpPost("{id}/items")]
    public IActionResult AddOrderItem(Guid id, [FromBody] OrderAddOrderItemRequest request)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Order>();
        var parent = objectSpace.GetObjectByKey<Order>(id);
        if (parent == null) return NotFound(new { error = "Order not found" });

        var item = objectSpace.CreateObject<OrderItem>();
        item.Order = parent;
        item.Quantity = request.Quantity;
        item.Price = request.Price;
        item.Product = objectSpace.GetObjectByKey<Product>(request.ProductId);

        objectSpace.CommitChanges();
        return Ok(new { item.Oid });
    }

    /// <summary>
    /// Update a Items item.
    /// </summary>
    [HttpPut("{id}/items/{itemId}")]
    public IActionResult UpdateOrderItem(Guid id, Guid itemId, [FromBody] OrderUpdateOrderItemRequest request)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(itemId);
        if (item == null) return NotFound(new { error = "OrderItem not found" });
        if (item.Order?.Oid != id) return BadRequest(new { error = "Item does not belong to this Order" });

        item.Quantity = request.Quantity;
        item.Price = request.Price;
        item.Product = objectSpace.GetObjectByKey<Product>(request.ProductId);

        objectSpace.CommitChanges();
        return NoContent();
    }

    /// <summary>
    /// Delete a Items item.
    /// </summary>
    [HttpDelete("{id}/items/{itemId}")]
    public IActionResult DeleteOrderItem(Guid id, Guid itemId)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(itemId);
        if (item == null) return NotFound();
        if (item.Order?.Oid != id) return BadRequest(new { error = "Item does not belong to this Order" });

        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for Order Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class OrderDto
{
    public string OrderNo { get; set; } = string.Empty;
    public DateTime? OrderDate { get; set; }
    public Guid? customerId { get; set; }
}

/// <summary>
/// Detailed response DTO with all relations.
/// </summary>
public class OrderDetailsDto
{
    public Guid Oid { get; set; }
    public string OrderNo { get; set; } = string.Empty;
    public DateTime? OrderDate { get; set; }
    public decimal TotalAmount { get; set; }
    public OrderCustomerRefDto? Customer { get; set; }
    public List<OrderOrderItemItemDto> Items { get; set; } = new();
}

public class OrderCustomerRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class OrderOrderItemItemDto
{
    public Guid Oid { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public decimal LineTotal { get; set; }
    public Guid ProductId { get; set; }
    public string? productName { get; set; }
}

public class OrderAddOrderItemRequest
{
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public Guid ProductId { get; set; }
}

public class OrderUpdateOrderItemRequest
{
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public Guid ProductId { get; set; }
}

