// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 15:32:06

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class OrderItemsController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public OrderItemsController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var items = objectSpace.GetObjectsQuery<OrderItem>()
            .Select(e => new
            {
                e.Oid,
                e.Quantity,
                e.Price,
                e.LineTotal,
                orderId = e.Order != null ? e.Order.Oid : (Guid?)null,
                OrderName = e.Order != null ? e.Order.OrderNo : null,
                productId = e.Product != null ? e.Product.Oid : (Guid?)null,
                ProductName = e.Product != null ? e.Product.Name : null,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.Quantity,
            item.Price,
            item.LineTotal,
            orderId = item.Order?.Oid,
            orderName = item.Order?.OrderNo,
            productId = item.Product?.Oid,
            productName = item.Product?.Name,
        });
    }

    /// <summary>
    /// Get entity with full details including relations.
    /// </summary>
    [HttpGet("{id}/details")]
    public IActionResult GetDetails(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(id);
        if (item == null) return NotFound();

        return Ok(new OrderItemDetailsDto
        {
            Oid = item.Oid,
            Quantity = item.Quantity,
            Price = item.Price,
            LineTotal = item.LineTotal,
            Order = item.Order != null ? new OrderItemOrderRefDto
            {
                Oid = item.Order.Oid,
                Name = item.Order.OrderNo ?? string.Empty,
            } : null,
            Product = item.Product != null ? new OrderItemProductRefDto
            {
                Oid = item.Product.Oid,
                Name = item.Product.Name ?? string.Empty,
            } : null,
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] OrderItemDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.CreateObject<OrderItem>();
        item.Quantity = dto.Quantity;
        item.Price = dto.Price;

        // Set Order reference
        if (dto.orderId.HasValue)
        {
            item.Order = objectSpace.GetObjectByKey<Order>(dto.orderId.Value);
        }

        // Set Product reference
        if (dto.productId.HasValue)
        {
            item.Product = objectSpace.GetObjectByKey<Product>(dto.productId.Value);
        }

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] OrderItemDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(id);
        if (item == null) return NotFound();
        item.Quantity = dto.Quantity;
        item.Price = dto.Price;

        // Update Order reference
        if (dto.orderId.HasValue)
        {
            item.Order = objectSpace.GetObjectByKey<Order>(dto.orderId.Value);
        }
        else
        {
            item.Order = null;
        }

        // Update Product reference
        if (dto.productId.HasValue)
        {
            item.Product = objectSpace.GetObjectByKey<Product>(dto.productId.Value);
        }
        else
        {
            item.Product = null;
        }

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<OrderItem>();
        var item = objectSpace.GetObjectByKey<OrderItem>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for OrderItem Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class OrderItemDto
{
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public Guid? orderId { get; set; }
    public Guid? productId { get; set; }
}

/// <summary>
/// Detailed response DTO with all relations.
/// </summary>
public class OrderItemDetailsDto
{
    public Guid Oid { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public decimal LineTotal { get; set; }
    public OrderItemOrderRefDto? Order { get; set; }
    public OrderItemProductRefDto? Product { get; set; }
}

public class OrderItemOrderRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class OrderItemProductRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

