// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 22:03:33

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class ProductsController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public ProductsController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Product>();
        var items = objectSpace.GetObjectsQuery<Product>()
            .Select(e => new
            {
                e.Oid,
                e.SKU,
                e.Name,
                e.StandardCost,
                e.StockQuantity,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Product>();
        var item = objectSpace.GetObjectByKey<Product>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.SKU,
            item.Name,
            item.StandardCost,
            item.StockQuantity,
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] ProductDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Product>();
        var item = objectSpace.CreateObject<Product>();
        item.SKU = dto.SKU;
        item.Name = dto.Name;
        item.StandardCost = dto.StandardCost;
        item.StockQuantity = dto.StockQuantity;

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] ProductDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Product>();
        var item = objectSpace.GetObjectByKey<Product>(id);
        if (item == null) return NotFound();
        item.SKU = dto.SKU;
        item.Name = dto.Name;
        item.StandardCost = dto.StandardCost;
        item.StockQuantity = dto.StockQuantity;

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Product>();
        var item = objectSpace.GetObjectByKey<Product>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for Product Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class ProductDto
{
    public string SKU { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public decimal StandardCost { get; set; }
    public int StockQuantity { get; set; }
}

