// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 22:03:33

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class PurchaseOrdersController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public PurchaseOrdersController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var items = objectSpace.GetObjectsQuery<PurchaseOrder>()
            .Select(e => new
            {
                e.Oid,
                e.PONumber,
                e.OrderDate,
                e.Status,
                e.TotalAmount,
                supplierId = e.Supplier != null ? e.Supplier.Oid : (Guid?)null,
                SupplierName = e.Supplier != null ? e.Supplier.Name : null,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.PONumber,
            item.OrderDate,
            item.Status,
            item.TotalAmount,
            supplierId = item.Supplier?.Oid,
            supplierName = item.Supplier?.Name,
        });
    }

    /// <summary>
    /// Get entity with full details including relations.
    /// </summary>
    [HttpGet("{id}/details")]
    public IActionResult GetDetails(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (item == null) return NotFound();

        return Ok(new PurchaseOrderDetailsDto
        {
            Oid = item.Oid,
            PONumber = item.PONumber,
            OrderDate = item.OrderDate,
            Status = item.Status,
            TotalAmount = item.TotalAmount,
            Supplier = item.Supplier != null ? new PurchaseOrderSupplierRefDto
            {
                Oid = item.Supplier.Oid,
                Name = item.Supplier.Name ?? string.Empty,
            } : null,
            Items = item.Items?.Select(d => new PurchaseOrderPurchaseOrderItemItemDto
            {
                Oid = d.Oid,
                Quantity = d.Quantity,
                UnitPrice = d.UnitPrice,
                Subtotal = d.Subtotal,
                ProductId = d.Product?.Oid ?? Guid.Empty,
                productName = d.Product?.Name,
            }).ToList() ?? new(),
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] PurchaseOrderDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.CreateObject<PurchaseOrder>();
        item.PONumber = dto.PONumber;
        item.OrderDate = dto.OrderDate ?? DateTime.Today;
        item.Status = dto.Status;

        // Set Supplier reference
        if (dto.supplierId.HasValue)
        {
            item.Supplier = objectSpace.GetObjectByKey<Supplier>(dto.supplierId.Value);
        }

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] PurchaseOrderDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (item == null) return NotFound();
        item.PONumber = dto.PONumber;
        item.OrderDate = dto.OrderDate ?? DateTime.Today;
        item.Status = dto.Status;

        // Update Supplier reference
        if (dto.supplierId.HasValue)
        {
            item.Supplier = objectSpace.GetObjectByKey<Supplier>(dto.supplierId.Value);
        }
        else
        {
            item.Supplier = null;
        }

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

    // ============ Items Detail Endpoints ============

    /// <summary>
    /// Get all Items items for this entity.
    /// </summary>
    [HttpGet("{id}/items")]
    public IActionResult GetItems(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var item = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (item == null) return NotFound();

        var items = item.Items?.Select(d => new { d.Oid, d.Quantity, d.UnitPrice, d.Subtotal, ProductId = d.Product?.Oid ?? Guid.Empty, productName = d.Product?.Name }).ToList() ?? new();
        return Ok(items);
    }

    /// <summary>
    /// Add a new Items item.
    /// </summary>
    [HttpPost("{id}/items")]
    public IActionResult AddPurchaseOrderItem(Guid id, [FromBody] PurchaseOrderAddPurchaseOrderItemRequest request)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrder>();
        var parent = objectSpace.GetObjectByKey<PurchaseOrder>(id);
        if (parent == null) return NotFound(new { error = "PurchaseOrder not found" });

        var item = objectSpace.CreateObject<PurchaseOrderItem>();
        item.PurchaseOrder = parent;
        item.Quantity = request.Quantity;
        item.UnitPrice = request.UnitPrice;
        item.Product = objectSpace.GetObjectByKey<Product>(request.ProductId);

        objectSpace.CommitChanges();
        return Ok(new { item.Oid });
    }

    /// <summary>
    /// Update a Items item.
    /// </summary>
    [HttpPut("{id}/items/{itemId}")]
    public IActionResult UpdatePurchaseOrderItem(Guid id, Guid itemId, [FromBody] PurchaseOrderUpdatePurchaseOrderItemRequest request)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(itemId);
        if (item == null) return NotFound(new { error = "PurchaseOrderItem not found" });
        if (item.PurchaseOrder?.Oid != id) return BadRequest(new { error = "Item does not belong to this PurchaseOrder" });

        item.Quantity = request.Quantity;
        item.UnitPrice = request.UnitPrice;
        item.Product = objectSpace.GetObjectByKey<Product>(request.ProductId);

        objectSpace.CommitChanges();
        return NoContent();
    }

    /// <summary>
    /// Delete a Items item.
    /// </summary>
    [HttpDelete("{id}/items/{itemId}")]
    public IActionResult DeletePurchaseOrderItem(Guid id, Guid itemId)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(itemId);
        if (item == null) return NotFound();
        if (item.PurchaseOrder?.Oid != id) return BadRequest(new { error = "Item does not belong to this PurchaseOrder" });

        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for PurchaseOrder Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class PurchaseOrderDto
{
    public string PONumber { get; set; } = string.Empty;
    public DateTime? OrderDate { get; set; }
    public PurchaseStatus Status { get; set; }
    public Guid? supplierId { get; set; }
}

/// <summary>
/// Detailed response DTO with all relations.
/// </summary>
public class PurchaseOrderDetailsDto
{
    public Guid Oid { get; set; }
    public string PONumber { get; set; } = string.Empty;
    public DateTime? OrderDate { get; set; }
    public PurchaseStatus Status { get; set; }
    public decimal TotalAmount { get; set; }
    public PurchaseOrderSupplierRefDto? Supplier { get; set; }
    public List<PurchaseOrderPurchaseOrderItemItemDto> Items { get; set; } = new();
}

public class PurchaseOrderSupplierRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class PurchaseOrderPurchaseOrderItemItemDto
{
    public Guid Oid { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal Subtotal { get; set; }
    public Guid ProductId { get; set; }
    public string? productName { get; set; }
}

public class PurchaseOrderAddPurchaseOrderItemRequest
{
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public Guid ProductId { get; set; }
}

public class PurchaseOrderUpdatePurchaseOrderItemRequest
{
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public Guid ProductId { get; set; }
}

