// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 17:40:23

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class PurchaseOrderItemsController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public PurchaseOrderItemsController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var items = objectSpace.GetObjectsQuery<PurchaseOrderItem>()
            .Select(e => new
            {
                e.Oid,
                e.Quantity,
                e.UnitPrice,
                e.Subtotal,
                purchaseOrderId = e.PurchaseOrder != null ? e.PurchaseOrder.Oid : (Guid?)null,
                PurchaseOrderName = e.PurchaseOrder != null ? e.PurchaseOrder.PONumber : null,
                productId = e.Product != null ? e.Product.Oid : (Guid?)null,
                ProductName = e.Product != null ? e.Product.Name : null,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.Quantity,
            item.UnitPrice,
            item.Subtotal,
            purchaseOrderId = item.PurchaseOrder?.Oid,
            purchaseOrderName = item.PurchaseOrder?.PONumber,
            productId = item.Product?.Oid,
            productName = item.Product?.Name,
        });
    }

    /// <summary>
    /// Get entity with full details including relations.
    /// </summary>
    [HttpGet("{id}/details")]
    public IActionResult GetDetails(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(id);
        if (item == null) return NotFound();

        return Ok(new PurchaseOrderItemDetailsDto
        {
            Oid = item.Oid,
            Quantity = item.Quantity,
            UnitPrice = item.UnitPrice,
            Subtotal = item.Subtotal,
            PurchaseOrder = item.PurchaseOrder != null ? new PurchaseOrderItemPurchaseOrderRefDto
            {
                Oid = item.PurchaseOrder.Oid,
                Name = item.PurchaseOrder.PONumber ?? string.Empty,
            } : null,
            Product = item.Product != null ? new PurchaseOrderItemProductRefDto
            {
                Oid = item.Product.Oid,
                Name = item.Product.Name ?? string.Empty,
            } : null,
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] PurchaseOrderItemDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.CreateObject<PurchaseOrderItem>();
        item.Quantity = dto.Quantity;
        item.UnitPrice = dto.UnitPrice;

        // Set PurchaseOrder reference
        if (dto.purchaseOrderId.HasValue)
        {
            item.PurchaseOrder = objectSpace.GetObjectByKey<PurchaseOrder>(dto.purchaseOrderId.Value);
        }

        // Set Product reference
        if (dto.productId.HasValue)
        {
            item.Product = objectSpace.GetObjectByKey<Product>(dto.productId.Value);
        }

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] PurchaseOrderItemDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(id);
        if (item == null) return NotFound();
        item.Quantity = dto.Quantity;
        item.UnitPrice = dto.UnitPrice;

        // Update PurchaseOrder reference
        if (dto.purchaseOrderId.HasValue)
        {
            item.PurchaseOrder = objectSpace.GetObjectByKey<PurchaseOrder>(dto.purchaseOrderId.Value);
        }
        else
        {
            item.PurchaseOrder = null;
        }

        // Update Product reference
        if (dto.productId.HasValue)
        {
            item.Product = objectSpace.GetObjectByKey<Product>(dto.productId.Value);
        }
        else
        {
            item.Product = null;
        }

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<PurchaseOrderItem>();
        var item = objectSpace.GetObjectByKey<PurchaseOrderItem>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for PurchaseOrderItem Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class PurchaseOrderItemDto
{
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public Guid? purchaseOrderId { get; set; }
    public Guid? productId { get; set; }
}

/// <summary>
/// Detailed response DTO with all relations.
/// </summary>
public class PurchaseOrderItemDetailsDto
{
    public Guid Oid { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal Subtotal { get; set; }
    public PurchaseOrderItemPurchaseOrderRefDto? PurchaseOrder { get; set; }
    public PurchaseOrderItemProductRefDto? Product { get; set; }
}

public class PurchaseOrderItemPurchaseOrderRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class PurchaseOrderItemProductRefDto
{
    public Guid Oid { get; set; }
    public string Name { get; set; } = string.Empty;
}

