// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 22:03:33

using DevExpress.ExpressApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using XekuII.ApiHost.BusinessObjects;

namespace XekuII.ApiHost.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class SuppliersController : ControllerBase
{
    private readonly IObjectSpaceFactory _objectSpaceFactory;

    public SuppliersController(IObjectSpaceFactory objectSpaceFactory)
    {
        _objectSpaceFactory = objectSpaceFactory;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Supplier>();
        var items = objectSpace.GetObjectsQuery<Supplier>()
            .Select(e => new
            {
                e.Oid,
                e.Name,
                e.ContactPerson,
                e.Phone,
                e.Address,
            })
            .ToList();
        return Ok(items);
    }

    [HttpGet("{id}")]
    public IActionResult GetById(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Supplier>();
        var item = objectSpace.GetObjectByKey<Supplier>(id);
        if (item == null) return NotFound();
        return Ok(new
        {
            item.Oid,
            item.Name,
            item.ContactPerson,
            item.Phone,
            item.Address,
        });
    }

    [HttpPost]
    public IActionResult Create([FromBody] SupplierDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Supplier>();
        var item = objectSpace.CreateObject<Supplier>();
        item.Name = dto.Name;
        item.ContactPerson = dto.ContactPerson;
        item.Phone = dto.Phone;
        item.Address = dto.Address;

        objectSpace.CommitChanges();
        return CreatedAtAction(nameof(GetById), new { id = item.Oid }, new { item.Oid });
    }

    [HttpPut("{id}")]
    public IActionResult Update(Guid id, [FromBody] SupplierDto dto)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Supplier>();
        var item = objectSpace.GetObjectByKey<Supplier>(id);
        if (item == null) return NotFound();
        item.Name = dto.Name;
        item.ContactPerson = dto.ContactPerson;
        item.Phone = dto.Phone;
        item.Address = dto.Address;

        objectSpace.CommitChanges();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public IActionResult Delete(Guid id)
    {
        using var objectSpace = _objectSpaceFactory.CreateObjectSpace<Supplier>();
        var item = objectSpace.GetObjectByKey<Supplier>(id);
        if (item == null) return NotFound();
        objectSpace.Delete(item);
        objectSpace.CommitChanges();
        return NoContent();
    }

}

/// <summary>
/// DTO for Supplier Create/Update operations.
/// Calculated and readonly fields are excluded.
/// </summary>
public class SupplierDto
{
    public string Name { get; set; } = string.Empty;
    public string ContactPerson { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string Address { get; set; } = string.Empty;
}

