entity: Product
caption: 產品
dbTable: Products
fields:
  - name: Code
    type: string
    required: true
    length: 20
    label: 產品編號
  - name: Name
    type: string
    required: true
    length: 100
    label: 產品名稱
  - name: Price
    type: decimal
    label: 定價
    default: "0"
  - name: Description
    type: string
    length: 500
    label: 說明
ui:
  list:
    columns: [Code, Name, Price]
