using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;

namespace XekuII.Generator.Generators;

/// <summary>
/// Generates typed API client from EntityDefinition.
/// Output: {entity}.api.generated.ts
/// </summary>
public class ApiClientGenerator
{
    private const string Indent = "  ";

    public string Generate(EntityDefinition entity, Dictionary<string, EntityDefinition>? entityMap = null)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var pluralName = Pluralize(entityName);
        var camelName = ToCamelCase(entityName);
        var endpoint = $"/{ToCamelCase(pluralName)}";
        var details = entity.Relations.Where(r => r.Type == "detail").ToList();

        // Header
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import { apiClient } from \"@/lib/api-client\";");
        var typeImports = new List<string> { entityName };
        if (details.Count > 0)
            typeImports.Add($"{entityName}Details");
        typeImports.Add($"Create{entityName}Dto");
        typeImports.Add($"Update{entityName}Dto");
        foreach (var detail in details)
        {
            typeImports.Add($"{detail.Target}Summary");
            typeImports.Add($"Create{detail.Target}ItemDto");
            typeImports.Add($"Update{detail.Target}ItemDto");
        }
        sb.AppendLine($"import type {{ {string.Join(", ", typeImports)} }} from \"../types/{ToKebabCase(entityName)}.types.generated\";");
        sb.AppendLine();

        // API object
        sb.AppendLine($"const BASE = \"{endpoint}\";");
        sb.AppendLine();
        sb.AppendLine($"export const {camelName}Api = {{");

        // GET all
        sb.AppendLine($"{Indent}getAll: (params?: Record<string, unknown>) =>");
        sb.AppendLine($"{Indent}{Indent}apiClient.get<{entityName}[]>(BASE, {{ params }}).then(r => r.data),");
        sb.AppendLine();

        // GET by id
        sb.AppendLine($"{Indent}getById: (id: string) =>");
        sb.AppendLine($"{Indent}{Indent}apiClient.get<{entityName}>(`${{BASE}}/${{id}}`).then(r => r.data),");
        sb.AppendLine();

        // GET details
        if (details.Count > 0)
        {
            sb.AppendLine($"{Indent}getDetails: (id: string) =>");
            sb.AppendLine($"{Indent}{Indent}apiClient.get<{entityName}Details>(`${{BASE}}/${{id}}/details`).then(r => r.data),");
            sb.AppendLine();
        }

        // POST
        sb.AppendLine($"{Indent}create: (data: Create{entityName}Dto) =>");
        sb.AppendLine($"{Indent}{Indent}apiClient.post<{{ oid: string }}>(BASE, data).then(r => r.data),");
        sb.AppendLine();

        // PUT
        sb.AppendLine($"{Indent}update: (id: string, data: Update{entityName}Dto) =>");
        sb.AppendLine($"{Indent}{Indent}apiClient.put(`${{BASE}}/${{id}}`, data).then(r => r.data),");
        sb.AppendLine();

        // DELETE
        sb.AppendLine($"{Indent}delete: (id: string) =>");
        sb.AppendLine($"{Indent}{Indent}apiClient.delete(`${{BASE}}/${{id}}`).then(r => r.data),");

        // Detail CRUD endpoints
        foreach (var detail in details)
        {
            var detailCamel = ToCamelCase(detail.Name);

            // GET items list
            sb.AppendLine();
            sb.AppendLine($"{Indent}get{detail.Name}: (id: string) =>");
            sb.AppendLine($"{Indent}{Indent}apiClient.get<{detail.Target}Summary[]>(`${{BASE}}/${{id}}/{detailCamel}`).then(r => r.data),");

            // POST add item
            sb.AppendLine();
            sb.AppendLine($"{Indent}add{detail.Target}: (id: string, data: Create{detail.Target}ItemDto) =>");
            sb.AppendLine($"{Indent}{Indent}apiClient.post<{{ oid: string }}>(`${{BASE}}/${{id}}/{detailCamel}`, data).then(r => r.data),");

            // PUT update item
            sb.AppendLine();
            sb.AppendLine($"{Indent}update{detail.Target}: (id: string, itemId: string, data: Update{detail.Target}ItemDto) =>");
            sb.AppendLine($"{Indent}{Indent}apiClient.put(`${{BASE}}/${{id}}/{detailCamel}/${{itemId}}`, data).then(r => r.data),");

            // DELETE item
            sb.AppendLine();
            sb.AppendLine($"{Indent}delete{detail.Target}: (id: string, itemId: string) =>");
            sb.AppendLine($"{Indent}{Indent}apiClient.delete(`${{BASE}}/${{id}}/{detailCamel}/${{itemId}}`).then(r => r.data),");
        }

        sb.AppendLine("};");
        sb.AppendLine();

        return sb.ToString();
    }

}
