using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;

namespace XekuII.Generator.Generators;

/// <summary>
/// Generates REST API Controllers from EntityDefinition.
/// Supports basic CRUD, reference relations, detail (master-detail) relations, and enum types.
/// </summary>
public class ControllerCodeGenerator
{
    private const string Indent = "    ";

    // Track enum names defined in the current entity for type mapping
    private HashSet<string> _entityEnumNames = new();
    private Dictionary<string, EntityDefinition>? _entityMap;

    /// <summary>
    /// Generate a complete API Controller for an entity.
    /// </summary>
    public string Generate(EntityDefinition entity, string boNamespace = "XekuII.Generated", string controllerNamespace = "XekuII.ApiHost.Controllers", Dictionary<string, EntityDefinition>? entityMap = null)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var pluralName = Pluralize(entityName);

        // Store entity map for cross-entity lookups
        _entityMap = entityMap;

        // Build enum names set for type mapping
        _entityEnumNames = entity.Enums?.Select(e => e.Name).ToHashSet(StringComparer.OrdinalIgnoreCase) ?? new();

        // Derive services namespace from controller namespace
        var servicesNamespace = controllerNamespace.Replace(".Controllers", ".Services");

        // File header
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine("// Generated at: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine();

        // Usings
        sb.AppendLine("using DevExpress.ExpressApp;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine($"using {boNamespace};");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {controllerNamespace};");
        sb.AppendLine();

        // Controller class
        sb.AppendLine("[Authorize]");
        sb.AppendLine("[ApiController]");
        sb.AppendLine($"[Route(\"api/[controller]\")]");
        sb.AppendLine($"public class {pluralName}Controller : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine($"{Indent}private readonly IObjectSpaceFactory _objectSpaceFactory;");
        sb.AppendLine();
        sb.AppendLine($"{Indent}public {pluralName}Controller(IObjectSpaceFactory objectSpaceFactory)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}_objectSpaceFactory = objectSpaceFactory;");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        // GET all
        GenerateGetAll(sb, entity);

        // GET by id
        GenerateGetById(sb, entity);

        // GET details (with relations)
        if (HasRelations(entity))
        {
            GenerateGetDetails(sb, entity);
        }

        // POST
        GeneratePost(sb, entity);

        // PUT
        GeneratePut(sb, entity);

        // DELETE
        GenerateDelete(sb, entity);

        // Detail relations CRUD endpoints
        foreach (var detail in entity.Relations.Where(r => r.Type.ToLower() == "detail"))
        {
            GenerateDetailEndpoints(sb, entity, detail);
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // DTO classes
        GenerateDto(sb, entity);
        GenerateDetailDtos(sb, entity);

        return sb.ToString();
    }

    private bool HasRelations(EntityDefinition entity) =>
        entity.Relations != null && entity.Relations.Count > 0;

    private IEnumerable<RelationDefinition> GetReferences(EntityDefinition entity) =>
        entity.Relations?.Where(r => r.Type.ToLower() == "reference") ?? Enumerable.Empty<RelationDefinition>();

    private IEnumerable<RelationDefinition> GetDetails(EntityDefinition entity) =>
        entity.Relations?.Where(r => r.Type.ToLower() == "detail") ?? Enumerable.Empty<RelationDefinition>();

    private void GenerateGetAll(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);

        sb.AppendLine($"{Indent}[HttpGet]");
        sb.AppendLine($"{Indent}public IActionResult GetAll()");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var items = objectSpace.GetObjectsQuery<{entityName}>()");
        sb.AppendLine($"{Indent}{Indent}{Indent}.Select(e => new");
        sb.AppendLine($"{Indent}{Indent}{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}e.Oid,");
        foreach (var field in entity.Fields)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}e.{field.Name},");
        }
        // Include reference IDs and names
        foreach (var reference in references)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{reference.Name}Id = e.{reference.Name} != null ? e.{reference.Name}.Oid : (Guid?)null,");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{reference.Name}Name = e.{reference.Name} != null ? e.{reference.Name}.ToString() : null,");
        }
        sb.AppendLine($"{Indent}{Indent}{Indent}}})");
        sb.AppendLine($"{Indent}{Indent}{Indent}.ToList();");
        sb.AppendLine($"{Indent}{Indent}return Ok(items);");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GenerateGetById(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);

        sb.AppendLine($"{Indent}[HttpGet(\"{{id}}\")]");
        sb.AppendLine($"{Indent}public IActionResult GetById(Guid id)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");
        sb.AppendLine($"{Indent}{Indent}return Ok(new");
        sb.AppendLine($"{Indent}{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}{Indent}item.Oid,");
        foreach (var field in entity.Fields)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}item.{field.Name},");
        }
        // Include reference IDs and names
        foreach (var reference in references)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{reference.Name}Id = item.{reference.Name}?.Oid,");
            sb.AppendLine($"{Indent}{Indent}{Indent}{reference.Name}Name = item.{reference.Name}?.ToString(),");
        }
        sb.AppendLine($"{Indent}{Indent}}});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GenerateGetDetails(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);
        var details = GetDetails(entity);

        sb.AppendLine($"{Indent}/// <summary>");
        sb.AppendLine($"{Indent}/// Get entity with full details including relations.");
        sb.AppendLine($"{Indent}/// </summary>");
        sb.AppendLine($"{Indent}[HttpGet(\"{{id}}/details\")]");
        sb.AppendLine($"{Indent}public IActionResult GetDetails(Guid id)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}return Ok(new {entityName}DetailsDto");
        sb.AppendLine($"{Indent}{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}{Indent}Oid = item.Oid,");
        foreach (var field in entity.Fields)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{field.Name} = item.{field.Name},");
        }
        // Include reference objects
        foreach (var reference in references)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{reference.Name} = item.{reference.Name} != null ? new {entityName}{reference.Target}RefDto");
            sb.AppendLine($"{Indent}{Indent}{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}Oid = item.{reference.Name}.Oid,");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}Name = item.{reference.Name}.ToString() ?? string.Empty,");
            sb.AppendLine($"{Indent}{Indent}{Indent}}} : null,");
        }
        // Include detail collections
        foreach (var detail in details)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{detail.Name} = item.{detail.Name}?.Select(d => new {entityName}{detail.Target}ItemDto");
            sb.AppendLine($"{Indent}{Indent}{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}Oid = d.Oid,");
            if (_entityMap != null && _entityMap.TryGetValue(detail.Target, out var detailTargetEntity))
            {
                foreach (var f in detailTargetEntity.Fields)
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{f.Name} = d.{f.Name},");

                // Include reference fields from detail entity (exclude back-reference to parent)
                var detailRefs = detailTargetEntity.Relations
                    .Where(r => r.Type == "reference" && !string.Equals(r.Target, entity.Entity, StringComparison.OrdinalIgnoreCase))
                    .ToList();
                foreach (var rel in detailRefs)
                {
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{rel.Name}Id = d.{rel.Name}?.Oid ?? Guid.Empty,");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{rel.Name}Name = d.{rel.Name}?.ToString(),");
                }
            }
            sb.AppendLine($"{Indent}{Indent}{Indent}}}).ToList() ?? new(),");
        }
        sb.AppendLine($"{Indent}{Indent}}});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GeneratePost(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);
        // Filter out calculated and readonly fields
        var writableFields = entity.Fields.Where(f => !IsCalculatedField(f) && !f.Readonly).ToList();

        sb.AppendLine($"{Indent}[HttpPost]");
        sb.AppendLine($"{Indent}public IActionResult Create([FromBody] {entityName}Dto dto)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.CreateObject<{entityName}>();");

        // Set fields
        foreach (var field in writableFields)
        {
            sb.AppendLine($"{Indent}{Indent}item.{field.Name} = dto.{field.Name};");
        }

        // Handle reference relations
        foreach (var reference in references)
        {
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}// Set {reference.Name} reference");
            sb.AppendLine($"{Indent}{Indent}if (dto.{reference.Name}Id.HasValue)");
            sb.AppendLine($"{Indent}{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}{Indent}item.{reference.Name} = objectSpace.GetObjectByKey<{reference.Target}>(dto.{reference.Name}Id.Value);");
            sb.AppendLine($"{Indent}{Indent}}}");
        }

        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return CreatedAtAction(nameof(GetById), new {{ id = item.Oid }}, new {{ item.Oid }});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GeneratePut(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);
        // Filter out calculated and readonly fields
        var writableFields = entity.Fields.Where(f => !IsCalculatedField(f) && !f.Readonly).ToList();

        sb.AppendLine($"{Indent}[HttpPut(\"{{id}}\")]");
        sb.AppendLine($"{Indent}public IActionResult Update(Guid id, [FromBody] {entityName}Dto dto)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");

        // Update fields (excluding calculated and readonly)
        foreach (var field in writableFields)
        {
            sb.AppendLine($"{Indent}{Indent}item.{field.Name} = dto.{field.Name};");
        }

        // Handle reference relations
        foreach (var reference in references)
        {
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}// Update {reference.Name} reference");
            sb.AppendLine($"{Indent}{Indent}if (dto.{reference.Name}Id.HasValue)");
            sb.AppendLine($"{Indent}{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}{Indent}item.{reference.Name} = objectSpace.GetObjectByKey<{reference.Target}>(dto.{reference.Name}Id.Value);");
            sb.AppendLine($"{Indent}{Indent}}}");
            sb.AppendLine($"{Indent}{Indent}else");
            sb.AppendLine($"{Indent}{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}{Indent}item.{reference.Name} = null;");
            sb.AppendLine($"{Indent}{Indent}}}");
        }

        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return NoContent();");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GenerateDelete(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        sb.AppendLine($"{Indent}[HttpDelete(\"{{id}}\")]");
        sb.AppendLine($"{Indent}public IActionResult Delete(Guid id)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");
        sb.AppendLine($"{Indent}{Indent}objectSpace.Delete(item);");
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return NoContent();");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GenerateDetailEndpoints(StringBuilder sb, EntityDefinition entity, RelationDefinition detail)
    {
        var entityName = entity.Entity;
        var detailName = detail.Name;
        var detailTarget = detail.Target;
        var detailNameLower = char.ToLower(detailName[0]) + detailName.Substring(1);

        sb.AppendLine($"{Indent}// ============ {detailName} Detail Endpoints ============");
        sb.AppendLine();

        // GET items
        sb.AppendLine($"{Indent}/// <summary>");
        sb.AppendLine($"{Indent}/// Get all {detailName} items for this entity.");
        sb.AppendLine($"{Indent}/// </summary>");
        sb.AppendLine($"{Indent}[HttpGet(\"{{id}}/{detailNameLower}\")]");
        sb.AppendLine($"{Indent}public IActionResult Get{detailName}(Guid id)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");
        sb.AppendLine();
        sb.Append($"{Indent}{Indent}var items = item.{detailName}?.Select(d => new {{ d.Oid");
        if (_entityMap != null && _entityMap.TryGetValue(detailTarget, out var targetDef))
        {
            foreach (var f in targetDef.Fields)
                sb.Append($", d.{f.Name}");

            // Include reference fields (exclude back-reference to parent)
            var targetRefs = targetDef.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList();
            foreach (var rel in targetRefs)
            {
                sb.Append($", {rel.Name}Id = d.{rel.Name}?.Oid ?? Guid.Empty");
                sb.Append($", {rel.Name}Name = d.{rel.Name}?.ToString()");
            }
        }
        sb.AppendLine(" }).ToList() ?? new();");
        sb.AppendLine($"{Indent}{Indent}return Ok(items);");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        // POST item
        sb.AppendLine($"{Indent}/// <summary>");
        sb.AppendLine($"{Indent}/// Add a new {detailName} item.");
        sb.AppendLine($"{Indent}/// </summary>");
        sb.AppendLine($"{Indent}[HttpPost(\"{{id}}/{detailNameLower}\")]");
        sb.AppendLine($"{Indent}public IActionResult Add{detailTarget}(Guid id, [FromBody] {entityName}Add{detailTarget}Request request)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{entityName}>();");
        sb.AppendLine($"{Indent}{Indent}var parent = objectSpace.GetObjectByKey<{entityName}>(id);");
        sb.AppendLine($"{Indent}{Indent}if (parent == null) return NotFound(new {{ error = \"{entityName} not found\" }});");
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.CreateObject<{detailTarget}>();");
        sb.AppendLine($"{Indent}{Indent}item.{entityName} = parent;");
        if (_entityMap != null && _entityMap.TryGetValue(detailTarget, out var postTargetDef))
        {
            foreach (var f in postTargetDef.Fields.Where(f => !IsCalculatedField(f) && !f.Readonly))
                sb.AppendLine($"{Indent}{Indent}item.{f.Name} = request.{f.Name};");

            // Set reference relations (exclude the back-reference to parent and detail relations)
            var targetRefs = postTargetDef.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList();
            foreach (var rel in targetRefs)
            {
                if (rel.Required)
                {
                    // Required reference: directly assign
                    sb.AppendLine($"{Indent}{Indent}item.{rel.Name} = objectSpace.GetObjectByKey<{rel.Target}>(request.{rel.Name}Id);");
                }
                else
                {
                    // Optional reference: check HasValue
                    sb.AppendLine($"{Indent}{Indent}if (request.{rel.Name}Id.HasValue)");
                    sb.AppendLine($"{Indent}{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}{Indent}item.{rel.Name} = objectSpace.GetObjectByKey<{rel.Target}>(request.{rel.Name}Id.Value);");
                    sb.AppendLine($"{Indent}{Indent}}}");
                }
            }
        }
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return Ok(new {{ item.Oid }});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        // PUT item
        sb.AppendLine($"{Indent}/// <summary>");
        sb.AppendLine($"{Indent}/// Update a {detailName} item.");
        sb.AppendLine($"{Indent}/// </summary>");
        sb.AppendLine($"{Indent}[HttpPut(\"{{id}}/{detailNameLower}/{{itemId}}\")]");
        sb.AppendLine($"{Indent}public IActionResult Update{detailTarget}(Guid id, Guid itemId, [FromBody] {entityName}Update{detailTarget}Request request)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{detailTarget}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{detailTarget}>(itemId);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound(new {{ error = \"{detailTarget} not found\" }});");
        sb.AppendLine($"{Indent}{Indent}if (item.{entityName}?.Oid != id) return BadRequest(new {{ error = \"Item does not belong to this {entityName}\" }});");
        sb.AppendLine();
        if (_entityMap != null && _entityMap.TryGetValue(detailTarget, out var putTargetDef))
        {
            foreach (var f in putTargetDef.Fields.Where(f => !IsCalculatedField(f) && !f.Readonly))
                sb.AppendLine($"{Indent}{Indent}item.{f.Name} = request.{f.Name};");

            // Update reference relations (exclude the back-reference to parent and detail relations)
            var targetRefs = putTargetDef.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList();
            foreach (var rel in targetRefs)
            {
                if (rel.Required)
                {
                    // Required reference: directly assign
                    sb.AppendLine($"{Indent}{Indent}item.{rel.Name} = objectSpace.GetObjectByKey<{rel.Target}>(request.{rel.Name}Id);");
                }
                else
                {
                    // Optional reference: check HasValue, allow null
                    sb.AppendLine($"{Indent}{Indent}if (request.{rel.Name}Id.HasValue)");
                    sb.AppendLine($"{Indent}{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}{Indent}item.{rel.Name} = objectSpace.GetObjectByKey<{rel.Target}>(request.{rel.Name}Id.Value);");
                    sb.AppendLine($"{Indent}{Indent}}}");
                    sb.AppendLine($"{Indent}{Indent}else");
                    sb.AppendLine($"{Indent}{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}{Indent}item.{rel.Name} = null;");
                    sb.AppendLine($"{Indent}{Indent}}}");
                }
            }
        }
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return NoContent();");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        // DELETE item
        sb.AppendLine($"{Indent}/// <summary>");
        sb.AppendLine($"{Indent}/// Delete a {detailName} item.");
        sb.AppendLine($"{Indent}/// </summary>");
        sb.AppendLine($"{Indent}[HttpDelete(\"{{id}}/{detailNameLower}/{{itemId}}\")]");
        sb.AppendLine($"{Indent}public IActionResult Delete{detailTarget}(Guid id, Guid itemId)");
        sb.AppendLine($"{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}using var objectSpace = _objectSpaceFactory.CreateObjectSpace<{detailTarget}>();");
        sb.AppendLine($"{Indent}{Indent}var item = objectSpace.GetObjectByKey<{detailTarget}>(itemId);");
        sb.AppendLine($"{Indent}{Indent}if (item == null) return NotFound();");
        sb.AppendLine($"{Indent}{Indent}if (item.{entityName}?.Oid != id) return BadRequest(new {{ error = \"Item does not belong to this {entityName}\" }});");
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}objectSpace.Delete(item);");
        sb.AppendLine($"{Indent}{Indent}objectSpace.CommitChanges();");
        sb.AppendLine($"{Indent}{Indent}return NoContent();");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();
    }

    private void GenerateDto(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);
        // Exclude calculated and readonly fields from Create/Update DTO
        var writableFields = entity.Fields.Where(f => !IsCalculatedField(f) && !f.Readonly).ToList();

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// DTO for {entityName} Create/Update operations.");
        sb.AppendLine($"/// Calculated and readonly fields are excluded.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public class {entityName}Dto");
        sb.AppendLine("{");

        // Fields (writable only)
        foreach (var field in writableFields)
        {
            var csharpType = MapType(field.Type);
            var defaultValue = GetDefaultValue(csharpType);
            sb.AppendLine($"{Indent}public {csharpType} {field.Name} {{ get; set; }}{defaultValue}");
        }

        // Reference IDs
        foreach (var reference in references)
        {
            sb.AppendLine($"{Indent}public Guid? {reference.Name}Id {{ get; set; }}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateDetailDtos(StringBuilder sb, EntityDefinition entity)
    {
        var entityName = entity.Entity;
        var references = GetReferences(entity);
        var details = GetDetails(entity);

        if (!HasRelations(entity)) return;

        // Details response DTO
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Detailed response DTO with all relations.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public class {entityName}DetailsDto");
        sb.AppendLine("{");
        sb.AppendLine($"{Indent}public Guid Oid {{ get; set; }}");
        foreach (var field in entity.Fields)
        {
            var csharpType = MapType(field.Type);
            var defaultValue = GetDefaultValue(csharpType);
            sb.AppendLine($"{Indent}public {csharpType} {field.Name} {{ get; set; }}{defaultValue}");
        }
        foreach (var reference in references)
        {
            sb.AppendLine($"{Indent}public {entityName}{reference.Target}RefDto? {reference.Name} {{ get; set; }}");
        }
        foreach (var detail in details)
        {
            sb.AppendLine($"{Indent}public List<{entityName}{detail.Target}ItemDto> {detail.Name} {{ get; set; }} = new();");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Reference DTOs
        foreach (var reference in references)
        {
            sb.AppendLine($"public class {entityName}{reference.Target}RefDto");
            sb.AppendLine("{");
            sb.AppendLine($"{Indent}public Guid Oid {{ get; set; }}");
            sb.AppendLine($"{Indent}public string Name {{ get; set; }} = string.Empty;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Detail item DTOs and request DTOs
        foreach (var detail in details)
        {
            EntityDefinition? targetEntity = null;
            _entityMap?.TryGetValue(detail.Target, out targetEntity);
            var targetFields = targetEntity?.Fields ?? new List<FieldDefinition>();

            // Build enum names from target entity for type mapping
            var targetEnumNames = targetEntity?.Enums?.Select(e => e.Name).ToHashSet(StringComparer.OrdinalIgnoreCase)
                ?? new HashSet<string>();
            var savedEnumNames = _entityEnumNames;
            _entityEnumNames = new HashSet<string>(_entityEnumNames, StringComparer.OrdinalIgnoreCase);
            foreach (var en in targetEnumNames) _entityEnumNames.Add(en);

            // ItemDto - all fields (read response)
            sb.AppendLine($"public class {entityName}{detail.Target}ItemDto");
            sb.AppendLine("{");
            sb.AppendLine($"{Indent}public Guid Oid {{ get; set; }}");
            foreach (var f in targetFields)
            {
                var csharpType = MapType(f.Type);
                var defaultValue = GetDefaultValue(csharpType);
                sb.AppendLine($"{Indent}public {csharpType} {f.Name} {{ get; set; }}{defaultValue}");
            }
            // Include reference fields (exclude back-reference to parent)
            var itemDtoRefs = targetEntity?.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList() ?? new List<RelationDefinition>();
            foreach (var rel in itemDtoRefs)
            {
                sb.AppendLine($"{Indent}public Guid {rel.Name}Id {{ get; set; }}");
                sb.AppendLine($"{Indent}public string? {rel.Name}Name {{ get; set; }}");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // AddRequest - writable fields only (exclude formula, readonly, and back-reference to parent)
            var writableTargetFields = targetFields.Where(f => !IsCalculatedField(f) && !f.Readonly).ToList();
            // Get reference relations from target entity (exclude back-reference to parent)
            var targetRefs = targetEntity?.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList() ?? new List<RelationDefinition>();

            sb.AppendLine($"public class {entityName}Add{detail.Target}Request");
            sb.AppendLine("{");
            foreach (var f in writableTargetFields)
            {
                var csharpType = MapType(f.Type);
                var defaultValue = GetDefaultValue(csharpType);
                sb.AppendLine($"{Indent}public {csharpType} {f.Name} {{ get; set; }}{defaultValue}");
            }
            // Add reference relation IDs
            foreach (var rel in targetRefs)
            {
                var nullable = rel.Required ? "" : "?";
                sb.AppendLine($"{Indent}public Guid{nullable} {rel.Name}Id {{ get; set; }}");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // UpdateRequest - same as AddRequest
            sb.AppendLine($"public class {entityName}Update{detail.Target}Request");
            sb.AppendLine("{");
            foreach (var f in writableTargetFields)
            {
                var csharpType = MapType(f.Type);
                var defaultValue = GetDefaultValue(csharpType);
                sb.AppendLine($"{Indent}public {csharpType} {f.Name} {{ get; set; }}{defaultValue}");
            }
            // Add reference relation IDs
            foreach (var rel in targetRefs)
            {
                var nullable = rel.Required ? "" : "?";
                sb.AppendLine($"{Indent}public Guid{nullable} {rel.Name}Id {{ get; set; }}");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            _entityEnumNames = savedEnumNames;
        }
    }

    private string GetDefaultValue(string csharpType) => csharpType switch
    {
        "string" => " = string.Empty;",
        "int" => "",
        "decimal" => "",
        "DateTime" => "",
        "bool" => "",
        "Guid" => "",
        _ => "" // Enums and other types don't need default values
    };

    /// <summary>
    /// Map YAML type to C# type. Supports built-in types and entity-defined enums.
    /// </summary>
    private string MapType(string yamlType)
    {
        // Check if it's an enum defined in this entity
        if (_entityEnumNames.Contains(yamlType))
        {
            return yamlType;
        }

        return yamlType.ToLower() switch
        {
            "string" => "string",
            "int" => "int",
            "decimal" => "decimal",
            "datetime" => "DateTime",
            "bool" => "bool",
            "guid" => "Guid",
            _ => yamlType // Return as-is for custom types/enums from other entities
        };
    }

    /// <summary>
    /// Check if a field is a calculated property (has a formula).
    /// </summary>
    private bool IsCalculatedField(FieldDefinition field)
    {
        return !string.IsNullOrEmpty(field.Formula);
    }
}
