using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;

namespace XekuII.Generator.Generators;

/// <summary>
/// Generates React list page components from EntityDefinition.
/// Output: {Entity}ListPage.generated.tsx
/// </summary>
public class ReactPageGenerator
{
    private const string Indent = "  ";

    private static readonly Dictionary<string, string> IconMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["BO_Product"] = "Package",
        ["BO_Customer"] = "Users",
        ["BO_Order"] = "ShoppingCart",
        ["BO_Invoice"] = "FileText",
        ["BO_Category"] = "Folder",
        ["BO_Report"] = "BarChart3",
        ["BO_Settings"] = "Settings",
        ["BO_Calendar"] = "Calendar",
        ["BO_Task"] = "CheckSquare",
        ["BO_Note"] = "StickyNote",
    };

    public string GenerateListPage(EntityDefinition entity)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = TypeScriptTypeGenerator.ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);

        // Resolve list columns
        var listColumns = ResolveListColumns(entity);
        var searchable = ResolveSearchable(entity);

        // Detect which features are used for conditional imports
        var hasBoolColumns = listColumns.Any(col => entity.Fields.Any(f => f.Name == col && f.Type.ToLower() == "bool"));
        var hasEnumColumns = listColumns.Any(col => entity.Fields.Any(f => f.Name == col &&
            entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true));
        var needsBadge = hasBoolColumns || hasEnumColumns;

        // Header
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate } from \"@tanstack/react-router\";");
        sb.AppendLine("import type { ColumnDef } from \"@tanstack/react-table\";");
        sb.AppendLine("import { useState } from \"react\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{ToKebabCase(entityName)}.api.generated\";");
        sb.AppendLine($"import type {{ {entityName} }} from \"../../types/{ToKebabCase(entityName)}.types.generated\";");

        // Import enum labels if entity has enum fields used in columns
        var enumColumnsUsed = listColumns
            .Select(col => entity.Fields.FirstOrDefault(f => f.Name == col))
            .Where(f => f != null && entity.Enums?.Any(e => e.Name.Equals(f!.Type, StringComparison.OrdinalIgnoreCase)) == true)
            .ToList();
        if (enumColumnsUsed.Count > 0)
        {
            var enumImports = entity.Enums!
                .Where(e => enumColumnsUsed.Any(f => f!.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .Select(e => e.Name + "Labels")
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{ToKebabCase(entityName)}.types.generated\";");
        }

        sb.AppendLine("import { EntityDataTable } from \"@/components/shared/EntityDataTable\";");
        sb.AppendLine("import { ConfirmDialog } from \"@/components/shared/ConfirmDialog\";");
        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { Button } from \"@/components/ui/button\";");
        if (needsBadge)
            sb.AppendLine("import { Badge } from \"@/components/ui/badge\";");
        sb.AppendLine("import { Tooltip, TooltipContent, TooltipTrigger } from \"@/components/ui/tooltip\";");
        sb.AppendLine("import { Plus, Eye, Pencil, Trash2 } from \"lucide-react\";");
        sb.AppendLine();

        // Page component - columns defined INSIDE to keep RowActions in scope
        var caption = entity.Caption ?? entityName;
        sb.AppendLine($"export function {entityName}ListPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const [deleteTarget, setDeleteTarget] = useState<{{ id: string; name: string }} | null>(null);");
        sb.AppendLine();

        // Query
        sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
        sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}s\"],");
        sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getAll(),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Delete mutation
        sb.AppendLine($"{Indent}const deleteMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: (id: string) => {camelName}Api.delete(id),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}setDeleteTarget(null);");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Map items: backend uses Oid, frontend uses id
        // eslint-disable-next-line to suppress any type warnings
        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const items = (data ?? []).map((item: any) => ({{");
        sb.AppendLine($"{Indent}{Indent}...item,");
        sb.AppendLine($"{Indent}{Indent}id: (item.oid ?? item.id) as string,");
        sb.AppendLine($"{Indent}}})) as {entityName}[];");
        sb.AppendLine();

        sb.AppendLine($"{Indent}if (isLoading) return <PageLoading />;");
        sb.AppendLine();

        // RowActions inline - defined before columns that reference it
        sb.AppendLine($"{Indent}function RowActions({{ item }}: {{ item: {entityName} }}) {{");
        sb.AppendLine($"{Indent}{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center gap-1\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8\" onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/$id\", params: {{ id: item.id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Eye className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>View</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8\" onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/$id/edit\", params: {{ id: item.id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Pencil className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>Edit</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8 text-destructive hover:text-destructive\" onClick={{() => setDeleteTarget({{ id: item.id, name: String(item.id) }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>Delete</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        // Column definitions - inside component so RowActions is in scope
        sb.AppendLine($"{Indent}const columns: ColumnDef<{entityName}, unknown>[] = [");
        foreach (var col in listColumns)
        {
            GenerateColumnDef(sb, col, entity, Indent);
        }
        sb.AppendLine($"{Indent}{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}{Indent}id: \"actions\",");
        sb.AppendLine($"{Indent}{Indent}{Indent}header: \"\",");
        sb.AppendLine($"{Indent}{Indent}{Indent}cell: ({{ row }}) => <RowActions item={{row.original}} />,");
        sb.AppendLine($"{Indent}{Indent}{Indent}enableSorting: false,");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}];");
        sb.AppendLine();

        // Return JSX
        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"space-y-4\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center justify-between\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{caption}</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Button onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/new\" }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Plus className=\"mr-2 h-4 w-4\" /> New");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");

        // DataTable
        var searchCol = searchable.Count > 0 ? TypeScriptTypeGenerator.ToCamelCase(searchable[0]) : null;
        sb.Append($"{Indent}{Indent}{Indent}<EntityDataTable columns={{columns}} data={{items}} pageSize={{20}}");
        if (searchCol != null)
            sb.Append($" searchColumn=\"{searchCol}\" searchPlaceholder=\"Search {caption}...\"");
        sb.AppendLine(" />");

        // Delete dialog
        sb.AppendLine($"{Indent}{Indent}{Indent}<ConfirmDialog");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}open={{!!deleteTarget}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onOpenChange={{(open) => !open && setDeleteTarget(null)}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}title=\"Delete {caption}\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}description={{`Are you sure you want to delete ${{deleteTarget?.name}}?`}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onConfirm={{() => deleteTarget && deleteMutation.mutate(deleteTarget.id)}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{deleteMutation.isPending}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}/>");
        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    private void GenerateColumnDef(StringBuilder sb, string fieldName, EntityDefinition entity, string baseIndent = "")
    {
        var field = entity.Fields.FirstOrDefault(f => f.Name == fieldName);
        var relation = entity.Relations.FirstOrDefault(r => r.Name == fieldName && r.Type == "reference");
        var camel = TypeScriptTypeGenerator.ToCamelCase(fieldName);
        var label = field?.Label ?? relation?.Label ?? fieldName;
        var I1 = baseIndent + Indent;
        var I2 = baseIndent + Indent + Indent;

        sb.AppendLine($"{I1}{{");
        sb.AppendLine($"{I2}accessorKey: \"{camel}\",");
        sb.AppendLine($"{I2}header: \"{EscapeString(label)}\",");

        if (field != null)
        {
            var enumDef = entity.Enums?.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));
            if (field.Type.ToLower() == "bool")
            {
                sb.AppendLine($"{I2}cell: ({{ getValue }}) => <Badge variant={{getValue() ? \"default\" : \"secondary\"}}>{{getValue() ? \"Yes\" : \"No\"}}</Badge>,");
            }
            else if (enumDef != null)
            {
                sb.AppendLine($"{I2}cell: ({{ getValue }}) => <Badge variant=\"outline\">{{({enumDef.Name}Labels as Record<number, string>)[getValue() as number] ?? String(getValue())}}</Badge>,");
            }
        }
        else if (relation != null)
        {
            // eslint-disable-next-line
            sb.AppendLine($"{I2}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
            sb.AppendLine($"{I2}accessorFn: (row: any) => row.{camel}Name ?? \"\",");
        }

        sb.AppendLine($"{I1}}},");
    }

    /// <summary>
    /// Generate routes.generated.tsx
    /// </summary>
    public string GenerateRoutes(List<EntityDefinition> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("import type { RouteComponent } from \"./route-types\";");

        foreach (var entity in entities)
        {
            var kebab = ToKebabCase(entity.Entity);
            sb.AppendLine($"import {{ {entity.Entity}ListPage }} from \"./pages/{kebab}/{entity.Entity}ListPage.generated\";");
            sb.AppendLine($"import {{ {entity.Entity}FormPage }} from \"./pages/{kebab}/{entity.Entity}FormPage.generated\";");
            sb.AppendLine($"import {{ {entity.Entity}DetailPage }} from \"./pages/{kebab}/{entity.Entity}DetailPage.generated\";");
        }

        sb.AppendLine();
        sb.AppendLine("export const generatedRoutes: RouteComponent[] = [");

        foreach (var entity in entities)
        {
            var kebabPlural = ToKebabCase(Pluralize(entity.Entity));
            sb.AppendLine($"  {{ path: \"/{kebabPlural}\", component: {entity.Entity}ListPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/new\", component: {entity.Entity}FormPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/$id\", component: {entity.Entity}DetailPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/$id/edit\", component: {entity.Entity}FormPage }},");
        }

        sb.AppendLine("];");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate navigation.generated.ts
    /// Excludes detail child entities (e.g., OrderLine) - they are only accessed from parent detail pages
    /// </summary>
    public string GenerateNavigation(List<EntityDefinition> entities)
    {
        // Find entities that are targets of "detail" relations (aggregated children)
        var detailTargets = entities
            .SelectMany(e => e.Relations.Where(r => r.Type == "detail").Select(r => r.Target))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        // Filter out detail children from navigation
        var navEntities = entities.Where(e => !detailTargets.Contains(e.Entity)).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("import type { NavItem } from \"@/lib/types\";");
        sb.AppendLine();
        sb.AppendLine("export const generatedNavItems: NavItem[] = [");

        foreach (var entity in navEntities)
        {
            var label = entity.Caption ?? entity.Entity;
            var path = $"/{ToKebabCase(Pluralize(entity.Entity))}";
            var icon = MapIcon(entity.Icon);
            sb.AppendLine($"  {{ label: \"{EscapeString(label)}\", path: \"{path}\", icon: \"{icon}\" }},");
        }

        sb.AppendLine("];");
        sb.AppendLine();

        return sb.ToString();
    }

    private List<string> ResolveListColumns(EntityDefinition entity)
    {
        if (entity.Ui?.List?.Columns is { Count: > 0 } cols)
            return cols;

        // Default: all non-calculated, non-detail fields + references
        var columns = entity.Fields
            .Where(f => string.IsNullOrEmpty(f.Formula))
            .Select(f => f.Name)
            .ToList();

        columns.AddRange(entity.Relations
            .Where(r => r.Type == "reference")
            .Select(r => r.Name));

        return columns;
    }

    private List<string> ResolveSearchable(EntityDefinition entity)
    {
        if (entity.Ui?.List?.Searchable is { Count: > 0 } s)
            return s;

        return entity.Fields
            .Where(f => f.Type.ToLower() == "string" && string.IsNullOrEmpty(f.Formula))
            .Select(f => f.Name)
            .Take(2)
            .ToList();
    }

    private static string MapIcon(string? xafIcon)
    {
        if (string.IsNullOrEmpty(xafIcon)) return "file";
        return IconMap.TryGetValue(xafIcon, out var icon)
            ? icon.ToLower().Replace("_", "-")
            : "file";
    }

    /// <summary>
    /// Generate {Entity}FormPage.generated.tsx - handles both create and edit modes.
    /// </summary>
    public string GenerateFormPage(EntityDefinition entity)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = TypeScriptTypeGenerator.ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);
        var kebab = ToKebabCase(entityName);
        var kebabPlural = ToKebabCase(pluralName);
        var caption = entity.Caption ?? entityName;

        // Writable fields (exclude formula + readonly)
        var writableFields = entity.Fields
            .Where(f => string.IsNullOrEmpty(f.Formula) && !f.Readonly)
            .ToList();
        var references = entity.Relations.Where(r => r.Type == "reference").ToList();

        // Header
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate, useParams } from \"@tanstack/react-router\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{kebab}.api.generated\";");
        sb.AppendLine($"import {{ create{entityName}Schema }} from \"../../schemas/{kebab}.schema.generated\";");
        sb.AppendLine($"import type {{ Create{entityName}Dto }} from \"../../types/{kebab}.types.generated\";");

        // Import enum constants + labels if needed
        var enumFields = writableFields
            .Where(f => entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true)
            .ToList();
        if (enumFields.Count > 0)
        {
            var enumImports = entity.Enums!
                .Where(e => enumFields.Any(f => f.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .SelectMany(e => new[] { e.Name, e.Name + "Labels" })
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{kebab}.types.generated\";");
        }

        var hasLayout = entity.Ui?.Form?.Layout is { Count: > 0 };
        var formImports = "EntityForm, type FieldConfig";
        if (hasLayout) formImports += ", type FormRowConfig";
        sb.AppendLine($"import {{ {formImports} }} from \"@/components/shared/EntityForm\";");
        if (references.Count > 0)
            sb.AppendLine("import { ReferenceSelect } from \"@/components/shared/ReferenceSelect\";");
        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { toast } from \"sonner\";");
        sb.AppendLine();

        // Field configs
        sb.AppendLine($"const fieldConfigs: FieldConfig[] = [");
        foreach (var field in writableFields)
        {
            var camelField = TypeScriptTypeGenerator.ToCamelCase(field.Name);
            var label = field.Label ?? field.Name;
            var fieldType = MapFieldType(field, entity.Enums);

            if (fieldType == "select" && entity.Enums != null)
            {
                var enumDef = entity.Enums.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));
                if (enumDef != null)
                {
                    // Enum select with custom render
                    sb.AppendLine($"{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}name: \"{camelField}\",");
                    sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(label)}\",");
                    sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
                    sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}) => (");
                    sb.AppendLine($"{Indent}{Indent}{Indent}<select");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}className=\"flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm\"");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{String(value ?? \"\")}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{(e) => onChange(Number(e.target.value))}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<option value=\"\">Select...</option>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{{Object.entries({enumDef.Name}Labels).map(([k, v]) => (");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<option key={{k}} value={{k}}>{{v}}</option>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}))}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}</select>");
                    sb.AppendLine($"{Indent}{Indent}),");
                    sb.AppendLine($"{Indent}}},");
                    continue;
                }
            }

            sb.AppendLine($"{Indent}{{ name: \"{camelField}\", label: \"{EscapeString(label)}\", type: \"{fieldType}\" as const }},");
        }

        // Reference fields as custom with ReferenceSelect
        foreach (var rel in references)
        {
            var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
            var label = rel.Label ?? rel.Name;
            var targetPlural = Pluralize(rel.Target);
            var endpoint = $"/{ToKebabCase(targetPlural)}";
            var lookupField = rel.LookupField ?? "name";

            sb.AppendLine($"{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}name: \"{camelRel}Id\",");
            sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(label)}\",");
            sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
            sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}) => (");
            sb.AppendLine($"{Indent}{Indent}{Indent}<ReferenceSelect");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}endpoint=\"{endpoint}\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{value as string | null}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{onChange as (v: string | null) => void}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}labelField=\"{TypeScriptTypeGenerator.ToCamelCase(lookupField)}\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}placeholder=\"Select {EscapeString(label)}...\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}/>");
            sb.AppendLine($"{Indent}{Indent}),");
            sb.AppendLine($"{Indent}}},");
        }

        sb.AppendLine("];");
        sb.AppendLine();

        // Form layout
        var formLayout = entity.Ui?.Form?.Layout;
        if (formLayout is { Count: > 0 })
        {
            sb.AppendLine("const formLayout: FormRowConfig[] = [");
            foreach (var row in formLayout)
            {
                var fieldNames = row.Row.Select(f => $"\"{TypeScriptTypeGenerator.ToCamelCase(f)}\"").ToList();
                sb.AppendLine($"{Indent}{{ fields: [{string.Join(", ", fieldNames)}] }},");
            }
            sb.AppendLine("];");
            sb.AppendLine();
        }

        // Page component
        sb.AppendLine($"export function {entityName}FormPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const params = useParams({{ strict: false }});");
        sb.AppendLine($"{Indent}const id = (params as Record<string, string | undefined>).id;");
        sb.AppendLine($"{Indent}const isEdit = !!id;");
        sb.AppendLine();

        // Load existing data for edit mode
        sb.AppendLine($"{Indent}const {{ data: existing, isLoading }} = useQuery({{");
        sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id],");
        sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getById(id!),");
        sb.AppendLine($"{Indent}{Indent}enabled: isEdit,");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Create mutation
        sb.AppendLine($"{Indent}const createMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: (data: Create{entityName}Dto) => {camelName}Api.create(data),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} created\");");
        sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to create {caption}\"),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Update mutation
        sb.AppendLine($"{Indent}const updateMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: (data: Create{entityName}Dto) => {camelName}Api.update(id!, data),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}\", id] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} updated\");");
        sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to update {caption}\"),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Loading state
        sb.AppendLine($"{Indent}if (isEdit && isLoading) return <PageLoading />;");
        sb.AppendLine();

        // Build default values
        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const ex = existing as any;");
        sb.AppendLine($"{Indent}const defaultValues = isEdit && ex");
        sb.AppendLine($"{Indent}{Indent}? {{");
        foreach (var field in writableFields)
        {
            var camelField = TypeScriptTypeGenerator.ToCamelCase(field.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelField}: ex.{camelField} ?? {GetDefaultForType(field, entity.Enums)},");
        }
        foreach (var rel in references)
        {
            var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelRel}Id: ex.{camelRel}?.id ?? ex.{camelRel}?.oid ?? null,");
        }
        sb.AppendLine($"{Indent}{Indent}}}");
        sb.AppendLine($"{Indent}{Indent}: {{");
        foreach (var field in writableFields)
        {
            var camelField = TypeScriptTypeGenerator.ToCamelCase(field.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelField}: {GetDefaultForType(field, entity.Enums)},");
        }
        foreach (var rel in references)
        {
            var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelRel}Id: null,");
        }
        sb.AppendLine($"{Indent}{Indent}}};");
        sb.AppendLine();

        // Return JSX
        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"max-w-2xl space-y-4\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{{isEdit ? \"Edit\" : \"New\"}} {caption}</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}<EntityForm");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}schema={{create{entityName}Schema}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}defaultValues={{defaultValues}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}fields={{fieldConfigs}}");
        if (formLayout is { Count: > 0 })
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}layout={{formLayout}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onSubmit={{(data) => isEdit ? updateMutation.mutate(data as Create{entityName}Dto) : createMutation.mutate(data as Create{entityName}Dto)}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{createMutation.isPending || updateMutation.isPending}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}submitLabel={{isEdit ? \"Update\" : \"Create\"}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onCancel={{() => navigate({{ to: \"/{kebabPlural}\" }})}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}/>");
        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate {Entity}DetailPage.generated.tsx - displays entity details with related data.
    /// </summary>
    public string GenerateDetailPage(EntityDefinition entity, Dictionary<string, EntityDefinition>? entityMap = null)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = TypeScriptTypeGenerator.ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);
        var kebab = ToKebabCase(entityName);
        var kebabPlural = ToKebabCase(pluralName);
        var caption = entity.Caption ?? entityName;

        var details = entity.Relations.Where(r => r.Type == "detail").ToList();
        var hasDetails = details.Count > 0;

        // Header
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate, useParams } from \"@tanstack/react-router\";");
        sb.AppendLine("import { useState } from \"react\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{kebab}.api.generated\";");

        // Type imports (only types actually referenced in the component code)
        var typeImports = new List<string>();
        foreach (var detail in details)
        {
            typeImports.Add($"{detail.Target}Summary");
            typeImports.Add($"Create{detail.Target}ItemDto");
        }
        if (typeImports.Count > 0)
            sb.AppendLine($"import type {{ {string.Join(", ", typeImports)} }} from \"../../types/{kebab}.types.generated\";");

        // Schema imports for detail items
        if (hasDetails)
        {
            var schemaImports = details
                .Select(d => $"create{d.Target}ItemSchema")
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", schemaImports)} }} from \"../../schemas/{kebab}.schema.generated\";");
        }

        // Detect which features are used for conditional imports
        var hasBoolFields = entity.Fields.Any(f => f.Type.ToLower() == "bool");
        var hasEnumFields = entity.Fields.Any(f => entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true);
        var needsBadge = hasBoolFields || hasEnumFields;

        // Import enum labels if entity has enum fields
        if (hasEnumFields)
        {
            var enumImports = entity.Enums!
                .Where(e => entity.Fields.Any(f => f.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .Select(e => e.Name + "Labels")
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{kebab}.types.generated\";");
        }

        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { ConfirmDialog } from \"@/components/shared/ConfirmDialog\";");
        if (hasDetails)
            sb.AppendLine("import { EntityForm, type FieldConfig } from \"@/components/shared/EntityForm\";");

        // Check if any detail target has reference relations (for ReferenceSelect import)
        var detailHasRefs = hasDetails && details.Any(d =>
        {
            if (entityMap == null || !entityMap.TryGetValue(d.Target, out var targetEntity)) return false;
            return targetEntity.Relations.Any(r =>
                r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase));
        });
        if (detailHasRefs)
            sb.AppendLine("import { ReferenceSelect } from \"@/components/shared/ReferenceSelect\";");

        sb.AppendLine("import { Button } from \"@/components/ui/button\";");
        sb.AppendLine("import { Card, CardContent, CardHeader, CardTitle } from \"@/components/ui/card\";");
        if (needsBadge)
            sb.AppendLine("import { Badge } from \"@/components/ui/badge\";");
        if (hasDetails)
        {
            sb.AppendLine("import { Dialog, DialogContent, DialogHeader, DialogTitle } from \"@/components/ui/dialog\";");
            sb.AppendLine("import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from \"@/components/ui/table\";");
        }
        sb.AppendLine($"import {{ Pencil, Trash2, ArrowLeft{(hasDetails ? ", Plus" : "")} }} from \"lucide-react\";");
        sb.AppendLine("import { toast } from \"sonner\";");
        sb.AppendLine();

        // Page component
        sb.AppendLine($"export function {entityName}DetailPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const {{ id }} = useParams({{ strict: false }}) as {{ id: string }};");
        sb.AppendLine($"{Indent}const [showDelete, setShowDelete] = useState(false);");

        // Detail CRUD state
        foreach (var detail in details)
        {
            sb.AppendLine($"{Indent}const [add{detail.Target}Open, setAdd{detail.Target}Open] = useState(false);");
            sb.AppendLine($"{Indent}const [delete{detail.Target}Target, setDelete{detail.Target}Target] = useState<string | null>(null);");
        }
        sb.AppendLine();

        // Query
        if (hasDetails)
        {
            sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
            sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id, \"details\"],");
            sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getDetails(id),");
            sb.AppendLine($"{Indent}}});");
        }
        else
        {
            sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
            sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id],");
            sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getById(id),");
            sb.AppendLine($"{Indent}}});");
        }
        sb.AppendLine();

        // Delete mutation (parent entity)
        sb.AppendLine($"{Indent}const deleteMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: () => {camelName}Api.delete(id),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} deleted\");");
        sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to delete {caption}\"),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        // Detail mutations (add + delete for each detail relation)
        foreach (var detail in details)
        {
            var detailLabel = detail.Label ?? detail.Name;

            // Add mutation
            sb.AppendLine($"{Indent}const add{detail.Target}Mutation = useMutation({{");
            sb.AppendLine($"{Indent}{Indent}mutationFn: (data: Create{detail.Target}ItemDto) => {camelName}Api.add{detail.Target}(id, data),");
            sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}\", id, \"details\"] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}setAdd{detail.Target}Open(false);");
            sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{EscapeString(detailLabel)} added\");");
            sb.AppendLine($"{Indent}{Indent}}},");
            sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to add {EscapeString(detailLabel)}\"),");
            sb.AppendLine($"{Indent}}});");
            sb.AppendLine();

            // Delete mutation
            sb.AppendLine($"{Indent}const delete{detail.Target}Mutation = useMutation({{");
            sb.AppendLine($"{Indent}{Indent}mutationFn: (itemId: string) => {camelName}Api.delete{detail.Target}(id, itemId),");
            sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}\", id, \"details\"] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}setDelete{detail.Target}Target(null);");
            sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{EscapeString(detailLabel)} deleted\");");
            sb.AppendLine($"{Indent}{Indent}}},");
            sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to delete {EscapeString(detailLabel)}\"),");
            sb.AppendLine($"{Indent}}});");
            sb.AppendLine();
        }

        sb.AppendLine($"{Indent}if (isLoading || !data) return <PageLoading />;");
        sb.AppendLine();

        // Cast data to any for flexible property access
        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const item = data as any;");
        sb.AppendLine();

        // Detail field configs for add forms
        foreach (var detail in details)
        {
            var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
            if (targetEntity == null) continue;

            var writableDetailFields = targetEntity.Fields
                .Where(f => string.IsNullOrEmpty(f.Formula) && !f.Readonly)
                .ToList();

            // Get reference relations from target entity (exclude back-reference to parent)
            var targetRefs = targetEntity.Relations
                .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                .ToList();

            sb.AppendLine($"{Indent}const {TypeScriptTypeGenerator.ToCamelCase(detail.Target)}Fields: FieldConfig[] = [");
            foreach (var f in writableDetailFields)
            {
                var camelF = TypeScriptTypeGenerator.ToCamelCase(f.Name);
                var fLabel = f.Label ?? f.Name;
                var fieldType = MapFieldType(f, targetEntity.Enums);
                sb.AppendLine($"{Indent}{Indent}{{ name: \"{camelF}\", label: \"{EscapeString(fLabel)}\", type: \"{fieldType}\" as const }},");
            }
            // Add reference fields with ReferenceSelect
            foreach (var rel in targetRefs)
            {
                var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
                var label = rel.Label ?? rel.Name;
                var targetPlural = Pluralize(rel.Target);
                var endpoint = $"/{ToKebabCase(targetPlural)}";
                var lookupField = rel.LookupField ?? "name";

                sb.AppendLine($"{Indent}{Indent}{{");
                sb.AppendLine($"{Indent}{Indent}{Indent}name: \"{camelRel}Id\",");
                sb.AppendLine($"{Indent}{Indent}{Indent}label: \"{EscapeString(label)}\",");
                sb.AppendLine($"{Indent}{Indent}{Indent}type: \"custom\" as const,");
                sb.AppendLine($"{Indent}{Indent}{Indent}render: ({{ value, onChange }}) => (");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<ReferenceSelect");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}endpoint=\"{endpoint}\"");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}value={{value as string | null}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}onChange={{onChange as (v: string | null) => void}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}labelField=\"{TypeScriptTypeGenerator.ToCamelCase(lookupField)}\"");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}placeholder=\"Select {EscapeString(label)}...\"");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}/>");
                sb.AppendLine($"{Indent}{Indent}{Indent}),");
                sb.AppendLine($"{Indent}{Indent}}},");
            }
            sb.AppendLine($"{Indent}];");
            sb.AppendLine();
        }

        // Return JSX
        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"space-y-6\">");

        // Header bar
        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center justify-between\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<div className=\"flex items-center gap-3\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" onClick={{() => navigate({{ to: \"/{kebabPlural}\" }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<ArrowLeft className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{caption} Detail</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<div className=\"flex gap-2\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"outline\" onClick={{() => navigate({{ to: \"/{kebabPlural}/$id/edit\", params: {{ id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Pencil className=\"mr-2 h-4 w-4\" /> Edit");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"destructive\" onClick={{() => setShowDelete(true)}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"mr-2 h-4 w-4\" /> Delete");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");
        sb.AppendLine();

        // Sections
        var sections = entity.Ui?.Detail?.Sections;
        if (sections is { Count: > 0 })
        {
            foreach (var section in sections)
            {
                if (!string.IsNullOrEmpty(section.Relation))
                {
                    // Detail relation section
                    var detail = details.FirstOrDefault(d => d.Name == section.Relation);
                    if (detail != null)
                    {
                        var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
                        GenerateDetailRelationSection(sb, section, detail, 3, targetEntity, entityName, camelName);
                    }
                }
                else if (section.Fields is { Count: > 0 })
                {
                    // Field section
                    GenerateFieldSection(sb, section, entity, 3);
                }
            }
        }
        else
        {
            // Default: single card with all fields
            sb.AppendLine($"{Indent}{Indent}{Indent}<Card>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<CardHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<CardTitle>Information</CardTitle>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</CardHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<CardContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<dl className=\"grid grid-cols-2 gap-4\">");

            foreach (var field in entity.Fields)
            {
                GenerateDetailField(sb, field, entity, 6);
            }

            // Reference fields
            foreach (var rel in entity.Relations.Where(r => r.Type == "reference"))
            {
                var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
                var relLabel = rel.Label ?? rel.Name;
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<div>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(relLabel)}</dt>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<dd className=\"mt-1\">{{String((item.{camelRel} as Record<string, unknown>)?.name ?? item.{camelRel} ?? \"-\")}}</dd>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</div>");
            }

            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</dl>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</CardContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}</Card>");

            // Default detail relation cards
            foreach (var detail in details)
            {
                var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
                sb.AppendLine();
                GenerateDefaultDetailRelationCard(sb, detail, 3, targetEntity);
            }
        }

        // Delete confirm dialog (parent)
        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}{Indent}<ConfirmDialog");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}open={{showDelete}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onOpenChange={{setShowDelete}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}title=\"Delete {caption}\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}description=\"Are you sure you want to delete this {caption.ToLower()}? This action cannot be undone.\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onConfirm={{() => deleteMutation.mutate()}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{deleteMutation.isPending}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}/>");

        // Detail dialogs (Add form dialog + Delete confirm dialog for each detail)
        foreach (var detail in details)
        {
            var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
            var detailLabel = detail.Label ?? detail.Name;
            var camelTarget = TypeScriptTypeGenerator.ToCamelCase(detail.Target);

            // Add dialog
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}{Indent}<Dialog open={{add{detail.Target}Open}} onOpenChange={{setAdd{detail.Target}Open}}>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<DialogContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<DialogHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<DialogTitle>Add {EscapeString(detailLabel)}</DialogTitle>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</DialogHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<EntityForm");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}schema={{create{detail.Target}ItemSchema}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}fields={{{camelTarget}Fields}}");

            // Build default values for the add form
            if (targetEntity != null)
            {
                var writableDetailFields = targetEntity.Fields
                    .Where(f => string.IsNullOrEmpty(f.Formula) && !f.Readonly)
                    .ToList();
                // Get reference relations (exclude back-reference to parent)
                var targetRefs = targetEntity.Relations
                    .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                    .ToList();

                sb.Append($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}defaultValues={{{{ ");
                var defaults = new List<string>();
                foreach (var f in writableDetailFields)
                {
                    var camelF = TypeScriptTypeGenerator.ToCamelCase(f.Name);
                    defaults.Add($"{camelF}: {GetDefaultForType(f, targetEntity.Enums)}");
                }
                // Add reference defaults (null)
                foreach (var rel in targetRefs)
                {
                    var camelRel = TypeScriptTypeGenerator.ToCamelCase(rel.Name);
                    defaults.Add($"{camelRel}Id: null");
                }
                sb.Append(string.Join(", ", defaults));
                sb.AppendLine(" }}");
            }

            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}onSubmit={{(data) => add{detail.Target}Mutation.mutate(data as Create{detail.Target}ItemDto)}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}loading={{add{detail.Target}Mutation.isPending}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}submitLabel=\"Add\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}onCancel={{() => setAdd{detail.Target}Open(false)}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}/>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</DialogContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}</Dialog>");

            // Delete confirm dialog for detail item
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}{Indent}<ConfirmDialog");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}open={{!!delete{detail.Target}Target}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onOpenChange={{(open) => !open && setDelete{detail.Target}Target(null)}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}title=\"Delete {EscapeString(detailLabel)}\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}description=\"Are you sure you want to delete this item?\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onConfirm={{() => delete{detail.Target}Target && delete{detail.Target}Mutation.mutate(delete{detail.Target}Target)}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{delete{detail.Target}Mutation.isPending}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}/>");
        }

        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    private void GenerateDetailField(StringBuilder sb, FieldDefinition field, EntityDefinition entity, int depth)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelField = TypeScriptTypeGenerator.ToCamelCase(field.Name);
        var label = field.Label ?? field.Name;
        var enumDef = entity.Enums?.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));

        sb.AppendLine($"{prefix}<div>");
        sb.AppendLine($"{prefix}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(label)}</dt>");

        if (field.Type.ToLower() == "bool")
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\"><Badge variant={{item.{camelField} ? \"default\" : \"secondary\"}}>{{item.{camelField} ? \"Yes\" : \"No\"}}</Badge></dd>");
        }
        else if (enumDef != null)
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\"><Badge variant=\"outline\">{{({enumDef.Name}Labels as Record<number, string>)[item.{camelField} as number] ?? String(item.{camelField})}}</Badge></dd>");
        }
        else
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\">{{String(item.{camelField} ?? \"-\")}}</dd>");
        }

        sb.AppendLine($"{prefix}</div>");
    }

    private void GenerateFieldSection(StringBuilder sb, DetailSection section, EntityDefinition entity, int depth)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(section.Title)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<dl className=\"grid grid-cols-2 gap-4\">");

        foreach (var fieldName in section.Fields!)
        {
            var field = entity.Fields.FirstOrDefault(f => f.Name == fieldName);
            var relation = entity.Relations.FirstOrDefault(r => r.Name == fieldName && r.Type == "reference");

            if (field != null)
            {
                GenerateDetailField(sb, field, entity, depth + 3);
            }
            else if (relation != null)
            {
                var camelRel = TypeScriptTypeGenerator.ToCamelCase(relation.Name);
                var relLabel = relation.Label ?? relation.Name;
                var innerPrefix = string.Concat(Enumerable.Repeat(Indent, depth + 3));
                sb.AppendLine($"{innerPrefix}<div>");
                sb.AppendLine($"{innerPrefix}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(relLabel)}</dt>");
                sb.AppendLine($"{innerPrefix}{Indent}<dd className=\"mt-1\">{{String((item.{camelRel} as Record<string, unknown>)?.name ?? item.{camelRel} ?? \"-\")}}</dd>");
                sb.AppendLine($"{innerPrefix}</div>");
            }
        }

        sb.AppendLine($"{prefix}{Indent}{Indent}</dl>");
        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }

    private void GenerateDetailRelationSection(StringBuilder sb, DetailSection section, RelationDefinition detail, int depth, EntityDefinition? targetEntity = null, string? parentEntityName = null, string? parentCamelName = null)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelDetail = TypeScriptTypeGenerator.ToCamelCase(detail.Name);

        // Get target entity fields for named columns
        var targetFields = targetEntity?.Fields ?? new List<FieldDefinition>();

        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader className=\"flex flex-row items-center justify-between\">");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(section.Title)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<Button size=\"sm\" onClick={{() => setAdd{detail.Target}Open(true)}}>");
        sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<Plus className=\"mr-2 h-4 w-4\" /> Add");
        sb.AppendLine($"{prefix}{Indent}{Indent}</Button>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");

        if (targetFields.Count > 0)
        {
            sb.AppendLine($"{prefix}{Indent}{Indent}<Table>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}<TableRow>");
            foreach (var f in targetFields)
            {
                var label = f.Label ?? f.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(label)}</TableHead>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead className=\"w-[50px]\"></TableHead>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{{(item.{camelDetail} as {detail.Target}Summary[] | undefined)?.map((row) => (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow key={{row.id ?? (row as any).oid}}>");
            foreach (var f in targetFields)
            {
                var camelF = TypeScriptTypeGenerator.ToCamelCase(f.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelF} ?? \"-\")}}</TableCell>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8 text-destructive\" onClick={{() => setDelete{detail.Target}Target(row.id ?? (row as any).oid)}}>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"h-4 w-4\" />");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</TableCell>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})) ?? (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow><TableCell colSpan={{{targetFields.Count + 1}}} className=\"text-center text-muted-foreground\">No items</TableCell></TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})}}");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}</Table>");
        }
        else
        {
            // Fallback: dynamic columns
            sb.AppendLine($"{prefix}{Indent}{Indent}<p className=\"text-muted-foreground\">No field definitions available</p>");
        }

        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }

    private void GenerateDefaultDetailRelationCard(StringBuilder sb, RelationDefinition detail, int depth, EntityDefinition? targetEntity = null)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelDetail = TypeScriptTypeGenerator.ToCamelCase(detail.Name);
        var label = detail.Label ?? detail.Name;
        var targetFields = targetEntity?.Fields ?? new List<FieldDefinition>();

        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader className=\"flex flex-row items-center justify-between\">");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(label)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<Button size=\"sm\" onClick={{() => setAdd{detail.Target}Open(true)}}>");
        sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<Plus className=\"mr-2 h-4 w-4\" /> Add");
        sb.AppendLine($"{prefix}{Indent}{Indent}</Button>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");

        if (targetFields.Count > 0)
        {
            sb.AppendLine($"{prefix}{Indent}{Indent}<Table>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}<TableRow>");
            foreach (var f in targetFields)
            {
                var fLabel = f.Label ?? f.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(fLabel)}</TableHead>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead className=\"w-[50px]\"></TableHead>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{{(item.{camelDetail} as {detail.Target}Summary[] | undefined)?.map((row) => (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow key={{row.id ?? (row as any).oid}}>");
            foreach (var f in targetFields)
            {
                var camelF = TypeScriptTypeGenerator.ToCamelCase(f.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelF} ?? \"-\")}}</TableCell>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8 text-destructive\" onClick={{() => setDelete{detail.Target}Target(row.id ?? (row as any).oid)}}>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"h-4 w-4\" />");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</TableCell>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})) ?? (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow><TableCell colSpan={{{targetFields.Count + 1}}} className=\"text-center text-muted-foreground\">No items</TableCell></TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})}}");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}</Table>");
        }
        else
        {
            sb.AppendLine($"{prefix}{Indent}{Indent}<p className=\"text-muted-foreground\">No items</p>");
        }

        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }

    private static string MapFieldType(FieldDefinition field, List<EnumDefinition>? enums)
    {
        var enumNames = enums?.Select(e => e.Name).ToHashSet(StringComparer.OrdinalIgnoreCase)
                        ?? new HashSet<string>();
        if (enumNames.Contains(field.Type))
            return "select";

        return field.Type.ToLower() switch
        {
            "string" when field.Length is > 200 => "textarea",
            "string" => "text",
            "int" => "number",
            "decimal" => "number",
            "double" => "number",
            "bool" => "boolean",
            "datetime" => "date",
            _ => "text",
        };
    }

    private static string GetDefaultForType(FieldDefinition field, List<EnumDefinition>? enums)
    {
        var enumDef = enums?.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));

        if (!string.IsNullOrEmpty(field.Default))
        {
            // Enum default: look up the numeric value by member name
            if (enumDef != null)
            {
                var member = enumDef.Members.FirstOrDefault(m => m.Name.Equals(field.Default, StringComparison.OrdinalIgnoreCase));
                if (member != null)
                    return $"{enumDef.Name}.{member.Name}";
                return "0";
            }

            return field.Type.ToLower() switch
            {
                "string" => $"\"{field.Default}\"",
                "bool" => field.Default.ToLower(),
                "datetime" when field.Default.Equals("now", StringComparison.OrdinalIgnoreCase)
                    => "new Date().toISOString()",
                "datetime" => $"\"{field.Default}\"",
                _ => field.Default,
            };
        }

        if (enumDef != null)
            return "0";

        return field.Type.ToLower() switch
        {
            "string" => "\"\"",
            "int" => "0",
            "decimal" => "0",
            "double" => "0",
            "bool" => "false",
            "datetime" => "\"\"",
            "guid" => "\"\"",
            _ => "\"\"",
        };
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
