using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;
using static XekuII.Generator.Utilities.ReactGeneratorUtils;

namespace XekuII.Generator.Generators;

public class ReactDetailPageGenerator
{
    public string Generate(EntityDefinition entity, Dictionary<string, EntityDefinition>? entityMap = null)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);
        var kebab = ToKebabCase(entityName);
        var kebabPlural = ToKebabCase(pluralName);
        var caption = entity.Caption ?? entityName;

        var details = entity.Relations.Where(r => r.Type == "detail").ToList();
        var hasDetails = details.Count > 0;

        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate, useParams } from \"@tanstack/react-router\";");
        sb.AppendLine("import { useState } from \"react\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{kebab}.api.generated\";");

        var typeImports = new List<string>();
        foreach (var detail in details)
        {
            typeImports.Add($"{detail.Target}Summary");
        }
        if (typeImports.Count > 0)
            sb.AppendLine($"import type {{ {string.Join(", ", typeImports)} }} from \"../../types/{kebab}.types.generated\";");

        var hasBoolFields = entity.Fields.Any(f => f.Type.ToLower() == "bool");
        var hasEnumFields = entity.Fields.Any(f => entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true);
        var needsBadge = hasBoolFields || hasEnumFields;

        if (hasEnumFields)
        {
            var enumImports = entity.Enums!
                .Where(e => entity.Fields.Any(f => f.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .Select(e => e.Name + "Labels")
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{kebab}.types.generated\";");
        }

        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { ConfirmDialog } from \"@/components/shared/ConfirmDialog\";");

        sb.AppendLine("import { Button } from \"@/components/ui/button\";");
        sb.AppendLine("import { Card, CardContent, CardHeader, CardTitle } from \"@/components/ui/card\";");
        if (needsBadge)
            sb.AppendLine("import { Badge } from \"@/components/ui/badge\";");
        if (hasDetails)
            sb.AppendLine("import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from \"@/components/ui/table\";");
        sb.AppendLine("import { Pencil, Trash2, ArrowLeft } from \"lucide-react\";");
        sb.AppendLine("import { toast } from \"sonner\";");
        sb.AppendLine();

        sb.AppendLine($"export function {entityName}DetailPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const {{ id }} = useParams({{ strict: false }}) as {{ id: string }};");
        sb.AppendLine($"{Indent}const [showDelete, setShowDelete] = useState(false);");
        sb.AppendLine();

        if (hasDetails)
        {
            sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
            sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id, \"details\"],");
            sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getDetails(id),");
            sb.AppendLine($"{Indent}}});");
        }
        else
        {
            sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
            sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id],");
            sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getById(id),");
            sb.AppendLine($"{Indent}}});");
        }
        sb.AppendLine();

        sb.AppendLine($"{Indent}const deleteMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: () => {camelName}Api.delete(id),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} deleted\");");
        sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to delete {caption}\"),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        sb.AppendLine($"{Indent}if (isLoading || !data) return <PageLoading />;");
        sb.AppendLine();

        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const item = data as any;");
        sb.AppendLine();

        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"space-y-6\">");

        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center justify-between\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<div className=\"flex items-center gap-3\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" onClick={{() => navigate({{ to: \"/{kebabPlural}\" }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<ArrowLeft className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{caption} Detail</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<div className=\"flex gap-2\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"outline\" onClick={{() => navigate({{ to: \"/{kebabPlural}/$id/edit\", params: {{ id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Pencil className=\"mr-2 h-4 w-4\" /> Edit");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"destructive\" onClick={{() => setShowDelete(true)}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"mr-2 h-4 w-4\" /> Delete");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");
        sb.AppendLine();

        var uiSections = entity.Ui?.Detail?.Sections;
        if (uiSections is { Count: > 0 })
        {
            foreach (var section in uiSections)
            {
                if (!string.IsNullOrEmpty(section.Relation))
                {
                    var detail = details.FirstOrDefault(d => d.Name == section.Relation);
                    if (detail != null)
                    {
                        var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
                        GenerateDetailRelationSection(sb, section, detail, 3, targetEntity, entityName, camelName);
                    }
                }
                else if (section.Fields is { Count: > 0 })
                {
                    GenerateFieldSection(sb, section, entity, 3);
                }
            }
        }
        else
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}<Card>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<CardHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<CardTitle>Information</CardTitle>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</CardHeader>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<CardContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<dl className=\"grid grid-cols-2 gap-4\">");

            foreach (var field in entity.Fields)
            {
                GenerateDetailField(sb, field, entity, 6);
            }

            foreach (var rel in entity.Relations.Where(r => r.Type == "reference"))
            {
                var camelRel = ToCamelCase(rel.Name);
                var relLabel = rel.Label ?? rel.Name;
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<div>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(relLabel)}</dt>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<dd className=\"mt-1\">{{String((item.{camelRel} as Record<string, unknown>)?.name ?? item.{camelRel} ?? \"-\")}}</dd>");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</div>");
            }

            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</dl>");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</CardContent>");
            sb.AppendLine($"{Indent}{Indent}{Indent}</Card>");

            foreach (var detail in details)
            {
                var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
                sb.AppendLine();
                GenerateDefaultDetailRelationCard(sb, detail, 3, targetEntity, entityName);
            }
        }

        sb.AppendLine();
        sb.AppendLine($"{Indent}{Indent}{Indent}<ConfirmDialog");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}open={{showDelete}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onOpenChange={{setShowDelete}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}title=\"Delete {caption}\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}description=\"Are you sure you want to delete this {caption.ToLower()}? This action cannot be undone.\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onConfirm={{() => deleteMutation.mutate()}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{deleteMutation.isPending}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}/>");

        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    private void GenerateDetailField(StringBuilder sb, FieldDefinition field, EntityDefinition entity, int depth)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelField = ToCamelCase(field.Name);
        var label = field.Label ?? field.Name;
        var enumDef = entity.Enums?.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));

        sb.AppendLine($"{prefix}<div>");
        sb.AppendLine($"{prefix}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(label)}</dt>");

        if (field.Type.ToLower() == "bool")
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\"><Badge variant={{item.{camelField} ? \"default\" : \"secondary\"}}>{{item.{camelField} ? \"Yes\" : \"No\"}}</Badge></dd>");
        }
        else if (enumDef != null)
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\"><Badge variant=\"outline\">{{({enumDef.Name}Labels as Record<number, string>)[item.{camelField} as number] ?? String(item.{camelField})}}</Badge></dd>");
        }
        else
        {
            sb.AppendLine($"{prefix}{Indent}<dd className=\"mt-1\">{{String(item.{camelField} ?? \"-\")}}</dd>");
        }

        sb.AppendLine($"{prefix}</div>");
    }

    private void GenerateFieldSection(StringBuilder sb, DetailSection section, EntityDefinition entity, int depth)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(section.Title)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<dl className=\"grid grid-cols-2 gap-4\">");

        foreach (var fieldName in section.Fields!)
        {
            var field = entity.Fields.FirstOrDefault(f => f.Name == fieldName);
            var relation = entity.Relations.FirstOrDefault(r => r.Name == fieldName && r.Type == "reference");

            if (field != null)
            {
                GenerateDetailField(sb, field, entity, depth + 3);
            }
            else if (relation != null)
            {
                var camelRel = ToCamelCase(relation.Name);
                var relLabel = relation.Label ?? relation.Name;
                var innerPrefix = string.Concat(Enumerable.Repeat(Indent, depth + 3));
                sb.AppendLine($"{innerPrefix}<div>");
                sb.AppendLine($"{innerPrefix}{Indent}<dt className=\"text-sm font-medium text-muted-foreground\">{EscapeString(relLabel)}</dt>");
                sb.AppendLine($"{innerPrefix}{Indent}<dd className=\"mt-1\">{{String((item.{camelRel} as Record<string, unknown>)?.name ?? item.{camelRel} ?? \"-\")}}</dd>");
                sb.AppendLine($"{innerPrefix}</div>");
            }
        }

        sb.AppendLine($"{prefix}{Indent}{Indent}</dl>");
        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }

    private void GenerateDetailRelationSection(StringBuilder sb, DetailSection section, RelationDefinition detail, int depth, EntityDefinition? targetEntity = null, string? parentEntityName = null, string? parentCamelName = null)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelDetail = ToCamelCase(detail.Name);

        var targetFields = targetEntity?.Fields ?? new List<FieldDefinition>();
        var targetRefs = targetEntity?.Relations
            .Where(r => r.Type == "reference" && !string.Equals(r.Target, parentEntityName ?? "", StringComparison.OrdinalIgnoreCase))
            .ToList() ?? new List<RelationDefinition>();

        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(section.Title)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");

        if (targetFields.Count > 0)
        {
            var totalCols = targetFields.Count + targetRefs.Count;
            sb.AppendLine($"{prefix}{Indent}{Indent}<Table>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}<TableRow>");
            foreach (var f in targetFields)
            {
                var label = f.Label ?? f.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(label)}</TableHead>");
            }
            foreach (var rel in targetRefs)
            {
                var relLabel = rel.Label ?? rel.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(relLabel)}</TableHead>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{{(item.{camelDetail} as {detail.Target}Summary[] | undefined)?.map((row) => (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow key={{row.id ?? (row as any).oid}}>");
            foreach (var f in targetFields)
            {
                var camelF = ToCamelCase(f.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelF} ?? \"-\")}}</TableCell>");
            }
            foreach (var rel in targetRefs)
            {
                var camelRel = ToCamelCase(rel.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelRel}Name ?? \"-\")}}</TableCell>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})) ?? (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow><TableCell colSpan={{{totalCols}}} className=\"text-center text-muted-foreground\">No items</TableCell></TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})}}");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}</Table>");
        }
        else
        {
            sb.AppendLine($"{prefix}{Indent}{Indent}<p className=\"text-muted-foreground\">No field definitions available</p>");
        }

        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }

    private void GenerateDefaultDetailRelationCard(StringBuilder sb, RelationDefinition detail, int depth, EntityDefinition? targetEntity = null, string? parentEntityName = null)
    {
        var prefix = string.Concat(Enumerable.Repeat(Indent, depth));
        var camelDetail = ToCamelCase(detail.Name);
        var label = detail.Label ?? detail.Name;
        var targetFields = targetEntity?.Fields ?? new List<FieldDefinition>();
        var targetRefs = targetEntity?.Relations
            .Where(r => r.Type == "reference" && !string.Equals(r.Target, parentEntityName ?? "", StringComparison.OrdinalIgnoreCase))
            .ToList() ?? new List<RelationDefinition>();

        sb.AppendLine($"{prefix}<Card>");
        sb.AppendLine($"{prefix}{Indent}<CardHeader>");
        sb.AppendLine($"{prefix}{Indent}{Indent}<CardTitle>{EscapeString(label)}</CardTitle>");
        sb.AppendLine($"{prefix}{Indent}</CardHeader>");
        sb.AppendLine($"{prefix}{Indent}<CardContent>");

        if (targetFields.Count > 0)
        {
            var totalCols = targetFields.Count + targetRefs.Count;
            sb.AppendLine($"{prefix}{Indent}{Indent}<Table>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}<TableRow>");
            foreach (var f in targetFields)
            {
                var fLabel = f.Label ?? f.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(fLabel)}</TableHead>");
            }
            foreach (var rel in targetRefs)
            {
                var relLabel = rel.Label ?? rel.Name;
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableHead>{EscapeString(relLabel)}</TableHead>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableHeader>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}<TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{{(item.{camelDetail} as {detail.Target}Summary[] | undefined)?.map((row) => (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow key={{row.id ?? (row as any).oid}}>");
            foreach (var f in targetFields)
            {
                var camelF = ToCamelCase(f.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelF} ?? \"-\")}}</TableCell>");
            }
            foreach (var rel in targetRefs)
            {
                var camelRel = ToCamelCase(rel.Name);
                sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<TableCell>{{String(row.{camelRel}Name ?? \"-\")}}</TableCell>");
            }
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}</TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})) ?? (");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent}{Indent}<TableRow><TableCell colSpan={{{totalCols}}} className=\"text-center text-muted-foreground\">No items</TableCell></TableRow>");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}{Indent})}}");
            sb.AppendLine($"{prefix}{Indent}{Indent}{Indent}</TableBody>");
            sb.AppendLine($"{prefix}{Indent}{Indent}</Table>");
        }
        else
        {
            sb.AppendLine($"{prefix}{Indent}{Indent}<p className=\"text-muted-foreground\">No items</p>");
        }

        sb.AppendLine($"{prefix}{Indent}</CardContent>");
        sb.AppendLine($"{prefix}</Card>");
    }
}
