using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;
using static XekuII.Generator.Utilities.ReactGeneratorUtils;

namespace XekuII.Generator.Generators;

public class ReactListPageGenerator
{
    public string Generate(EntityDefinition entity)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);

        var listColumns = ResolveListColumns(entity);
        var searchable = ResolveSearchable(entity);

        var hasBoolColumns = listColumns.Any(col => entity.Fields.Any(f => f.Name == col && f.Type.ToLower() == "bool"));
        var hasEnumColumns = listColumns.Any(col => entity.Fields.Any(f => f.Name == col &&
            entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true));
        var needsBadge = hasBoolColumns || hasEnumColumns;

        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate } from \"@tanstack/react-router\";");
        sb.AppendLine("import type { ColumnDef } from \"@tanstack/react-table\";");
        sb.AppendLine("import { useState } from \"react\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{ToKebabCase(entityName)}.api.generated\";");
        sb.AppendLine($"import type {{ {entityName} }} from \"../../types/{ToKebabCase(entityName)}.types.generated\";");

        var enumColumnsUsed = listColumns
            .Select(col => entity.Fields.FirstOrDefault(f => f.Name == col))
            .Where(f => f != null && entity.Enums?.Any(e => e.Name.Equals(f!.Type, StringComparison.OrdinalIgnoreCase)) == true)
            .ToList();
        if (enumColumnsUsed.Count > 0)
        {
            var enumImports = entity.Enums!
                .Where(e => enumColumnsUsed.Any(f => f!.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .Select(e => e.Name + "Labels")
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{ToKebabCase(entityName)}.types.generated\";");
        }

        sb.AppendLine("import { EntityDataTable } from \"@/components/shared/EntityDataTable\";");
        sb.AppendLine("import { ConfirmDialog } from \"@/components/shared/ConfirmDialog\";");
        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { Button } from \"@/components/ui/button\";");
        if (needsBadge)
            sb.AppendLine("import { Badge } from \"@/components/ui/badge\";");
        sb.AppendLine("import { Tooltip, TooltipContent, TooltipTrigger } from \"@/components/ui/tooltip\";");
        sb.AppendLine("import { Plus, Eye, Pencil, Trash2 } from \"lucide-react\";");
        sb.AppendLine();

        var caption = entity.Caption ?? entityName;
        sb.AppendLine($"export function {entityName}ListPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const [deleteTarget, setDeleteTarget] = useState<{{ id: string; name: string }} | null>(null);");
        sb.AppendLine();

        sb.AppendLine($"{Indent}const {{ data, isLoading }} = useQuery({{");
        sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}s\"],");
        sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getAll(),");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        sb.AppendLine($"{Indent}const deleteMutation = useMutation({{");
        sb.AppendLine($"{Indent}{Indent}mutationFn: (id: string) => {camelName}Api.delete(id),");
        sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
        sb.AppendLine($"{Indent}{Indent}{Indent}setDeleteTarget(null);");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const items = (data ?? []).map((item: any) => ({{");
        sb.AppendLine($"{Indent}{Indent}...item,");
        sb.AppendLine($"{Indent}{Indent}id: (item.oid ?? item.id) as string,");
        sb.AppendLine($"{Indent}}})) as {entityName}[];");
        sb.AppendLine();

        sb.AppendLine($"{Indent}if (isLoading) return <PageLoading />;");
        sb.AppendLine();

        sb.AppendLine($"{Indent}function RowActions({{ item }}: {{ item: {entityName} }}) {{");
        sb.AppendLine($"{Indent}{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center gap-1\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8\" onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/$id\", params: {{ id: item.id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Eye className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>View</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8\" onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/$id/edit\", params: {{ id: item.id }} }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Pencil className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>Edit</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipTrigger asChild>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Button variant=\"ghost\" size=\"icon\" className=\"h-8 w-8 text-destructive hover:text-destructive\" onClick={{() => setDeleteTarget({{ id: item.id, name: String(item.id) }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}<Trash2 className=\"h-4 w-4\" />");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}</TooltipTrigger>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<TooltipContent>Delete</TooltipContent>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Tooltip>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent}{Indent});");
        sb.AppendLine($"{Indent}}}");
        sb.AppendLine();

        sb.AppendLine($"{Indent}const columns: ColumnDef<{entityName}, unknown>[] = [");
        foreach (var col in listColumns)
        {
            GenerateColumnDef(sb, col, entity, Indent);
        }
        sb.AppendLine($"{Indent}{Indent}{{");
        sb.AppendLine($"{Indent}{Indent}{Indent}id: \"actions\",");
        sb.AppendLine($"{Indent}{Indent}{Indent}header: \"\",");
        sb.AppendLine($"{Indent}{Indent}{Indent}cell: ({{ row }}) => <RowActions item={{row.original}} />,");
        sb.AppendLine($"{Indent}{Indent}{Indent}enableSorting: false,");
        sb.AppendLine($"{Indent}{Indent}}},");
        sb.AppendLine($"{Indent}];");
        sb.AppendLine();

        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"space-y-4\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}<div className=\"flex items-center justify-between\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{caption}</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<Button onClick={{() => navigate({{ to: \"/{ToKebabCase(pluralName)}/new\" }})}}>");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<Plus className=\"mr-2 h-4 w-4\" /> New");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}</Button>");
        sb.AppendLine($"{Indent}{Indent}{Indent}</div>");

        var searchCol = searchable.Count > 0 ? ToCamelCase(searchable[0]) : null;
        sb.Append($"{Indent}{Indent}{Indent}<EntityDataTable columns={{columns}} data={{items}} pageSize={{20}}");
        if (searchCol != null)
            sb.Append($" searchColumn=\"{searchCol}\" searchPlaceholder=\"Search {caption}...\"");
        sb.AppendLine(" />");

        sb.AppendLine($"{Indent}{Indent}{Indent}<ConfirmDialog");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}open={{!!deleteTarget}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onOpenChange={{(open) => !open && setDeleteTarget(null)}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}title=\"Delete {caption}\"");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}description={{`Are you sure you want to delete ${{deleteTarget?.name}}?`}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onConfirm={{() => deleteTarget && deleteMutation.mutate(deleteTarget.id)}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{deleteMutation.isPending}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}/>");
        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    private void GenerateColumnDef(StringBuilder sb, string fieldName, EntityDefinition entity, string baseIndent = "")
    {
        var field = entity.Fields.FirstOrDefault(f => f.Name == fieldName);
        var relation = entity.Relations.FirstOrDefault(r => r.Name == fieldName && r.Type == "reference");
        var camel = ToCamelCase(fieldName);
        var label = field?.Label ?? relation?.Label ?? fieldName;
        var I1 = baseIndent + Indent;
        var I2 = baseIndent + Indent + Indent;

        sb.AppendLine($"{I1}{{");
        sb.AppendLine($"{I2}accessorKey: \"{camel}\",");
        sb.AppendLine($"{I2}header: \"{EscapeString(label)}\",");

        if (field != null)
        {
            var enumDef = entity.Enums?.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));
            if (field.Type.ToLower() == "bool")
            {
                sb.AppendLine($"{I2}cell: ({{ getValue }}) => <Badge variant={{getValue() ? \"default\" : \"secondary\"}}>{{getValue() ? \"Yes\" : \"No\"}}</Badge>,");
            }
            else if (enumDef != null)
            {
                sb.AppendLine($"{I2}cell: ({{ getValue }}) => <Badge variant=\"outline\">{{({enumDef.Name}Labels as Record<number, string>)[getValue() as number] ?? String(getValue())}}</Badge>,");
            }
        }
        else if (relation != null)
        {
            sb.AppendLine($"{I2}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
            sb.AppendLine($"{I2}accessorFn: (row: any) => row.{camel}Name ?? \"\",");
        }

        sb.AppendLine($"{I1}}},");
    }
}
