using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;
using static XekuII.Generator.Utilities.ReactGeneratorUtils;

namespace XekuII.Generator.Generators;

public class ReactMetadataGenerator
{
    public string GenerateRoutes(List<EntityDefinition> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("import type { RouteComponent } from \"./route-types\";");

        foreach (var entity in entities)
        {
            var kebab = ToKebabCase(entity.Entity);
            sb.AppendLine($"import {{ {entity.Entity}ListPage }} from \"./pages/{kebab}/{entity.Entity}ListPage.generated\";");
            sb.AppendLine($"import {{ {entity.Entity}FormPage }} from \"./pages/{kebab}/{entity.Entity}FormPage.generated\";");
            sb.AppendLine($"import {{ {entity.Entity}DetailPage }} from \"./pages/{kebab}/{entity.Entity}DetailPage.generated\";");
        }

        sb.AppendLine();
        sb.AppendLine("export const generatedRoutes: RouteComponent[] = [");

        foreach (var entity in entities)
        {
            var kebabPlural = ToKebabCase(Pluralize(entity.Entity));
            sb.AppendLine($"  {{ path: \"/{kebabPlural}\", component: {entity.Entity}ListPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/new\", component: {entity.Entity}FormPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/$id\", component: {entity.Entity}DetailPage }},");
            sb.AppendLine($"  {{ path: \"/{kebabPlural}/$id/edit\", component: {entity.Entity}FormPage }},");
        }

        sb.AppendLine("];");
        sb.AppendLine();

        return sb.ToString();
    }

    public string GenerateNavigation(List<EntityDefinition> entities)
    {
        var detailTargets = entities
            .SelectMany(e => e.Relations.Where(r => r.Type == "detail").Select(r => r.Target))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var navEntities = entities.Where(e => !detailTargets.Contains(e.Entity)).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("import type { NavItem } from \"@/lib/types\";");
        sb.AppendLine();
        sb.AppendLine("export const generatedNavItems: NavItem[] = [");

        foreach (var entity in navEntities)
        {
            var label = entity.Caption ?? entity.Entity;
            var path = $"/{ToKebabCase(Pluralize(entity.Entity))}";
            var icon = MapIcon(entity.Icon);
            sb.AppendLine($"  {{ label: \"{EscapeString(label)}\", path: \"{path}\", icon: \"{icon}\", entity: \"{entity.Entity}\" }},");
        }

        sb.AppendLine("];");
        sb.AppendLine();

        return sb.ToString();
    }
}
