using System.Text;
using XekuII.Generator.Models;
using static XekuII.Generator.Utilities.StringUtils;
using static XekuII.Generator.Utilities.ReactGeneratorUtils;

namespace XekuII.Generator.Generators;

public class ReactFormPageGenerator
{
    public string Generate(EntityDefinition entity, Dictionary<string, EntityDefinition>? entityMap = null)
    {
        var sb = new StringBuilder();
        var entityName = entity.Entity;
        var camelName = ToCamelCase(entityName);
        var pluralName = Pluralize(entityName);
        var kebab = ToKebabCase(entityName);
        var kebabPlural = ToKebabCase(pluralName);
        var caption = entity.Caption ?? entityName;

        var writableFields = entity.Fields
            .Where(f => string.IsNullOrEmpty(f.Formula) && !f.Readonly)
            .ToList();
        var references = entity.Relations.Where(r => r.Type == "reference").ToList();
        var details = entity.Relations.Where(r => r.Type == "detail").ToList();
        var hasDetails = details.Count > 0;

        sb.AppendLine("// Auto-generated by XekuII.Generator - DO NOT EDIT");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        if (hasDetails)
            sb.AppendLine("import { useQuery, useQueryClient } from \"@tanstack/react-query\";");
        else
            sb.AppendLine("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
        sb.AppendLine("import { useNavigate, useParams } from \"@tanstack/react-router\";");
        if (hasDetails)
            sb.AppendLine("import { useState, useEffect } from \"react\";");
        else
            sb.AppendLine("import { useEffect } from \"react\";");
        sb.AppendLine($"import {{ {camelName}Api }} from \"../../api/{kebab}.api.generated\";");
        sb.AppendLine($"import {{ create{entityName}Schema }} from \"../../schemas/{kebab}.schema.generated\";");
        sb.AppendLine($"import type {{ Create{entityName}Dto }} from \"../../types/{kebab}.types.generated\";");

        if (hasDetails)
        {
            var detailTypeImports = new List<string>();
            var detailSchemaImports = new List<string>();
            foreach (var detail in details)
            {
                detailTypeImports.Add($"Create{detail.Target}ItemDto");
                detailSchemaImports.Add($"create{detail.Target}ItemSchema");
            }
            sb.AppendLine($"import type {{ {string.Join(", ", detailTypeImports)} }} from \"../../types/{kebab}.types.generated\";");
            sb.AppendLine($"import {{ {string.Join(", ", detailSchemaImports)} }} from \"../../schemas/{kebab}.schema.generated\";");
            sb.AppendLine("import { InlineDetailTable, type InlineDetailItem, type InlineDetailColumn } from \"@/components/shared/InlineDetailTable\";");
        }

        var enumFields = writableFields
            .Where(f => entity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true)
            .ToList();
        if (enumFields.Count > 0)
        {
            var enumImports = entity.Enums!
                .Where(e => enumFields.Any(f => f.Type.Equals(e.Name, StringComparison.OrdinalIgnoreCase)))
                .SelectMany(e => new[] { e.Name, e.Name + "Labels" })
                .ToList();
            sb.AppendLine($"import {{ {string.Join(", ", enumImports)} }} from \"../../types/{kebab}.types.generated\";");
        }

        // --- 收集詳細實體使用的列舉 ---
        if (hasDetails && entityMap != null)
        {
            var detailEnums = new HashSet<string>();
            foreach (var detail in details)
            {
                if (entityMap.TryGetValue(detail.Target, out var te) && te.Enums != null)
                {
                    foreach (var e in te.Enums) detailEnums.Add(e.Name);
                }
            }
            if (detailEnums.Count > 0)
            {
                var detailEnumImports = detailEnums.SelectMany(e => new[] { e, e + "Labels" }).ToList();
                sb.AppendLine($"import {{ {string.Join(", ", detailEnumImports)} }} from \"../../types/{kebab}.types.generated\";");
            }
        }

        var hasLayout = entity.Ui?.Form?.Layout is { Count: > 0 };
        var formImports = "EntityForm, type FieldConfig";
        if (hasLayout) formImports += ", type FormRowConfig";
        sb.AppendLine($"import {{ {formImports} }} from \"@/components/shared/EntityForm\";");

        var detailHasRefs = hasDetails && details.Any(d =>
        {
            if (entityMap == null || !entityMap.TryGetValue(d.Target, out var te)) return false;
            return te.Relations.Any(r =>
                r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase));
        });
        if (references.Count > 0 || detailHasRefs)
            sb.AppendLine("import { ReferenceSelect } from \"@/components/shared/ReferenceSelect\";");
        sb.AppendLine("import { PageLoading } from \"@/components/shared/LoadingSpinner\";");
        sb.AppendLine("import { toast } from \"sonner\";");
        sb.AppendLine("import { useEntityPermissions } from \"@/hooks/usePermissions\";");
        if (hasDetails)
            sb.AppendLine("import { Input } from \"@/components/ui/input\";");
        sb.AppendLine();

        sb.AppendLine($"const fieldConfigs: FieldConfig[] = [");
        foreach (var field in writableFields)
        {
            var camelField = ToCamelCase(field.Name);
            var label = field.Label ?? field.Name;
            var fieldType = MapFieldType(field, entity.Enums);

            if (fieldType == "select" && entity.Enums != null)
            {
                var enumDef = entity.Enums.FirstOrDefault(e => e.Name.Equals(field.Type, StringComparison.OrdinalIgnoreCase));
                if (enumDef != null)
                {
                    sb.AppendLine($"{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}name: \"{camelField}\",");
                    sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(label)}\",");
                    sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
                    sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}) => (");
                    sb.AppendLine($"{Indent}{Indent}{Indent}<select");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}className=\"flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm\"");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{String(value ?? \"\")}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{(e) => onChange(e.target.value)}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<option value=\"\">Select...</option>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{{Object.entries({enumDef.Name}Labels).map(([k, v]) => (");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}<option key={{k}} value={{k}}>{{v}}</option>");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}))}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}</select>");
                    sb.AppendLine($"{Indent}{Indent}),");
                    sb.AppendLine($"{Indent}}},");
                    continue;
                }
            }

            sb.AppendLine($"{Indent}{{ name: \"{camelField}\", label: \"{EscapeString(label)}\", type: \"{fieldType}\" as const }},");
        }

        foreach (var rel in references)
        {
            var camelRel = ToCamelCase(rel.Name);
            var label = rel.Label ?? rel.Name;
            var targetPlural = Pluralize(rel.Target);
            var endpoint = $"/{ToKebabCase(targetPlural)}";
            var lookupField = rel.LookupField ?? "name";

            sb.AppendLine($"{Indent}{{");
            sb.AppendLine($"{Indent}{Indent}name: \"{camelRel}Id\",");
            sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(label)}\",");
            sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
            sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}) => (");
            sb.AppendLine($"{Indent}{Indent}{Indent}<ReferenceSelect");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}endpoint=\"{endpoint}\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{value as string | null}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{onChange as (v: string | null) => void}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}labelField=\"{ToCamelCase(lookupField)}\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}placeholder=\"Select {EscapeString(label)}...\"");
            sb.AppendLine($"{Indent}{Indent}{Indent}/>");
            sb.AppendLine($"{Indent}{Indent}),");
            sb.AppendLine($"{Indent}}},");
        }
        sb.AppendLine("];");
        sb.AppendLine();

        var formLayout = entity.Ui?.Form?.Layout;
        if (formLayout is { Count: > 0 })
        {
            sb.AppendLine("const formLayout: FormRowConfig[] = [");
            foreach (var row in formLayout)
            {
                var fieldNames = row.Row.Select(f =>
                {
                    var isRef = references.Any(r => string.Equals(r.Name, f, StringComparison.OrdinalIgnoreCase));
                    var mappedName = isRef ? ToCamelCase(f) + "Id" : ToCamelCase(f);
                    return $"\"{mappedName}\"";
                }).ToList();
                sb.AppendLine($"{Indent}{{ fields: [{string.Join(", ", fieldNames)}] }},");
            }
            sb.AppendLine("];");
            sb.AppendLine();
        }

        if (hasDetails)
        {
            foreach (var detail in details)
            {
                var targetEntity = entityMap != null && entityMap.TryGetValue(detail.Target, out var te) ? te : null;
                if (targetEntity == null) continue;

                var camelTarget = ToCamelCase(detail.Target);
                var targetRefs = targetEntity.Relations
                    .Where(r => r.Type == "reference" && !string.Equals(r.Target, entityName, StringComparison.OrdinalIgnoreCase))
                    .ToList();

                sb.AppendLine($"const {camelTarget}FieldConfigs: FieldConfig[] = [");
                foreach (var f in targetEntity.Fields)
                {
                    if (f.Readonly && string.IsNullOrEmpty(f.Formula)) continue;
                    
                    var camelF = ToCamelCase(f.Name);
                    var fLabel = f.Label ?? f.Name;
                    var fieldType = MapFieldType(f, targetEntity.Enums);
                    
                    if (!string.IsNullOrEmpty(f.Formula))
                    {
                        sb.AppendLine($"{Indent}{{ ");
                        sb.AppendLine($"{Indent}{Indent}name: \"{camelF}\", ");
                        sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(fLabel)}\", ");
                        sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
                        sb.AppendLine($"{Indent}{Indent}render: ({{ value }}) => <div className=\"py-2 px-3 bg-muted rounded-md font-medium text-right\">{{(Number(value) || 0).toLocaleString(undefined, {{ minimumFractionDigits: 2, maximumFractionDigits: 2 }})}}</div>");
                        sb.AppendLine($"{Indent}}},");
                        continue;
                    }

                    var dependentFormulas = targetEntity.Fields
                        .Where(other => !string.IsNullOrEmpty(other.Formula) && other.Formula.Contains($"[{f.Name}]"))
                        .ToList();

                    if (dependentFormulas.Any())
                    {
                        sb.AppendLine($"{Indent}{{ ");
                        sb.AppendLine($"{Indent}{Indent}name: \"{camelF}\", ");
                        sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(fLabel)}\", ");
                        sb.AppendLine($"{Indent}{Indent}type: \"{fieldType}\" as const,");
                        sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}, {{ setValue, getValues }}) => (");
                        sb.AppendLine($"{Indent}{Indent}{Indent}<Input ");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}type=\"number\" ");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{value as number || 0}} ");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{(e) => {{");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}const newVal = e.target.valueAsNumber || 0;");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}onChange(newVal);");
                        
                        foreach (var dep in dependentFormulas)
                        {
                            var camelDep = ToCamelCase(dep.Name);
                            var formula = dep.Formula!; 
                            if (formula.Contains("*"))
                            {
                                var parts = formula.Split('*').Select(p => p.Trim().Trim('[', ']')).ToList();
                                if (parts.Count == 2)
                                {
                                    var otherPart = parts.FirstOrDefault(p => !string.Equals(p, f.Name, StringComparison.OrdinalIgnoreCase));
                                    if (otherPart != null)
                                    {
                                        var camelOther = ToCamelCase(otherPart);
                                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}const otherVal = Number(getValues(\"{camelOther}\")) || 0;");
                                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}setValue(\"{camelDep}\", newVal * otherVal, {{ shouldValidate: true, shouldDirty: true }});");
                                    }
                                }
                            }
                        }
                        
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}}}}}");
                        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}placeholder=\"{EscapeString(fLabel)}\"");
                        sb.AppendLine($"{Indent}{Indent}{Indent}/>");
                        sb.AppendLine($"{Indent}{Indent}),");
                        sb.AppendLine($"{Indent}}},");
                    }
                    else
                    {
                        sb.AppendLine($"{Indent}{{ name: \"{camelF}\", label: \"{EscapeString(fLabel)}\", type: \"{fieldType}\" as const }},");
                    }
                }
                foreach (var rel in targetRefs)
                {
                    var camelRel = ToCamelCase(rel.Name);
                    var relLabel = rel.Label ?? rel.Name;
                    var targetPlural = Pluralize(rel.Target);
                    var endpoint = $"/{ToKebabCase(targetPlural)}";
                    var lookupField = rel.LookupField ?? "name";

                    sb.AppendLine($"{Indent}{{");
                    sb.AppendLine($"{Indent}{Indent}name: \"{camelRel}Id\",");
                    sb.AppendLine($"{Indent}{Indent}label: \"{EscapeString(relLabel)}\",");
                    sb.AppendLine($"{Indent}{Indent}type: \"custom\" as const,");
                    var camelRelName = ToCamelCase(rel.Name) + "Name";
                    sb.AppendLine($"{Indent}{Indent}render: ({{ value, onChange }}, {{ setValue }}) => (");
                    sb.AppendLine($"{Indent}{Indent}{Indent}<ReferenceSelect");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}endpoint=\"{endpoint}\"");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}value={{value as string | null}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onChange={{onChange as (v: string | null) => void}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onLabelChange={{(label) => setValue(\"{camelRelName}\", label, {{ shouldValidate: true, shouldDirty: true }})}}");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}labelField=\"{ToCamelCase(lookupField)}\"");
                    sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}placeholder=\"Select {EscapeString(relLabel)}...\"");
                    sb.AppendLine($"{Indent}{Indent}{Indent}/>");
                    sb.AppendLine($"{Indent}{Indent}),");
                    sb.AppendLine($"{Indent}}},");
                }
                sb.AppendLine("];");
                sb.AppendLine();

                sb.AppendLine($"const {camelTarget}Columns: InlineDetailColumn[] = [");
                foreach (var f in targetEntity.Fields)
                {
                    var camelF = ToCamelCase(f.Name);
                    var fLabel = f.Label ?? f.Name;
                    sb.AppendLine($"{Indent}{{ key: \"{camelF}\", header: \"{EscapeString(fLabel)}\" }},");
                }
                foreach (var rel in targetRefs)
                {
                    var camelRel = ToCamelCase(rel.Name);
                    var relLabel = rel.Label ?? rel.Name;
                    sb.AppendLine($"{Indent}{{ key: \"{camelRel}Name\", header: \"{EscapeString(relLabel)}\" }},");
                }
                sb.AppendLine("];");
                sb.AppendLine();

                sb.AppendLine($"const {camelTarget}Defaults: Record<string, unknown> = {{");
                foreach (var f in targetEntity.Fields)
                {
                    var camelF = ToCamelCase(f.Name);
                    var defaultValue = GetDefaultForType(f, targetEntity.Enums);
                    // 如果是列舉類型，確保使用 Enum.Member 格式
                    if (targetEntity.Enums?.Any(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase)) == true)
                    {
                        var enumDef = targetEntity.Enums.First(e => e.Name.Equals(f.Type, StringComparison.OrdinalIgnoreCase));
                        var defStr = f.Default ?? enumDef.Members.FirstOrDefault()?.Name ?? enumDef.Members.First().Name;
                        defaultValue = $"{enumDef.Name}.{defStr}";
                    }
                    sb.AppendLine($"{Indent}{camelF}: {defaultValue},");
                }
                foreach (var rel in targetRefs)
                {
                    var camelRel = ToCamelCase(rel.Name);
                    sb.AppendLine($"{Indent}{camelRel}Id: null,");
                    sb.AppendLine($"{Indent}{camelRel}Name: null,");
                }
                sb.AppendLine("};");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"export function {entityName}FormPage() {{");
        sb.AppendLine($"{Indent}const navigate = useNavigate();");
        sb.AppendLine($"{Indent}const queryClient = useQueryClient();");
        sb.AppendLine($"{Indent}const params = useParams({{ strict: false }});");
        sb.AppendLine($"{Indent}const id = (params as Record<string, string | undefined>).id;");
        sb.AppendLine($"{Indent}const isEdit = !!id;");
        sb.AppendLine($"{Indent}const {{ canCreate, canUpdate, loaded: permissionsLoaded }} = useEntityPermissions(\"{entityName}\");");
        if (hasDetails)
            sb.AppendLine($"{Indent}const [saving, setSaving] = useState(false);");
        sb.AppendLine();

        if (hasDetails)
        {
            foreach (var detail in details)
            {
                var camelTarget = ToCamelCase(detail.Target);
                sb.AppendLine($"{Indent}const [{camelTarget}Items, set{detail.Target}Items] = useState<InlineDetailItem[]>([]);");
            }
            sb.AppendLine($"{Indent}const [detailsLoaded, setDetailsLoaded] = useState(false);");
            sb.AppendLine();
        }

        sb.AppendLine($"{Indent}const {{ data: existing, isLoading }} = useQuery({{");
        sb.AppendLine($"{Indent}{Indent}queryKey: [\"{camelName}\", id],");
        sb.AppendLine($"{Indent}{Indent}queryFn: () => {camelName}Api.getById(id!),");
        sb.AppendLine($"{Indent}{Indent}enabled: isEdit,");
        sb.AppendLine($"{Indent}}});");
        sb.AppendLine();

        if (hasDetails)
        {
            sb.AppendLine($"{Indent}useEffect(() => {{");
            sb.AppendLine($"{Indent}{Indent}if (!isEdit || !id || detailsLoaded) return;");
            sb.AppendLine($"{Indent}{Indent}{camelName}Api.getDetails(id).then((data) => {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
            sb.AppendLine($"{Indent}{Indent}{Indent}const d = data as any;");
            foreach (var detail in details)
            {
                var camelDetail = ToCamelCase(detail.Name);
                sb.AppendLine($"{Indent}{Indent}{Indent}set{detail.Target}Items((d.{camelDetail} || []).map((item: any) => ({{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}...item,");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}_localId: crypto.randomUUID(),");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}_status: \"existing\" as const,");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}_serverId: item.oid ?? item.id,");
                sb.AppendLine($"{Indent}{Indent}{Indent}}})));");
            }
            sb.AppendLine($"{Indent}{Indent}{Indent}setDetailsLoaded(true);");
            sb.AppendLine($"{Indent}{Indent}}});");
            sb.AppendLine($"{Indent}}}, [isEdit, id, detailsLoaded]);");
            sb.AppendLine();

            sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
            sb.AppendLine($"{Indent}async function handleSubmit(masterData: any) {{");
            sb.AppendLine($"{Indent}{Indent}setSaving(true);");
            sb.AppendLine($"{Indent}{Indent}try {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}let masterId: string;");
            sb.AppendLine($"{Indent}{Indent}{Indent}if (isEdit) {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}await {camelName}Api.update(id!, masterData as Create{entityName}Dto);");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}masterId = id!;");
            sb.AppendLine($"{Indent}{Indent}{Indent}}} else {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}const result = await {camelName}Api.create(masterData as Create{entityName}Dto);");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}masterId = result.oid;");
            sb.AppendLine($"{Indent}{Indent}{Indent}}}");
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}{Indent}const failures: string[] = [];");
            foreach (var detail in details)
            {
                var camelTarget = ToCamelCase(detail.Target);
                var detailLabel = detail.Label ?? detail.Name;
                sb.AppendLine($"{Indent}{Indent}{Indent}for (const item of {camelTarget}Items.filter(i => i._status === \"deleted\" && i._serverId)) {{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}try {{ await {camelName}Api.delete{detail.Target}(masterId, item._serverId!); }}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}catch {{ failures.push(`Delete {EscapeString(detailLabel)} ${{item._serverId}}`); }}");
                sb.AppendLine($"{Indent}{Indent}{Indent}}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}for (const item of {camelTarget}Items.filter(i => i._status === \"modified\" && i._serverId)) {{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}try {{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}const dto = {{ ...item }} as any;");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}delete dto._localId; delete dto._status; delete dto._serverId; delete dto.id;");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}await {camelName}Api.update{detail.Target}(masterId, item._serverId!, dto);");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}}} catch {{ failures.push(`Update {EscapeString(detailLabel)}`); }}");
                sb.AppendLine($"{Indent}{Indent}{Indent}}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}for (const item of {camelTarget}Items.filter(i => i._status === \"new\")) {{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}try {{");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}const dto = {{ ...item }} as any;");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}delete dto._localId; delete dto._status; delete dto._serverId;");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}await {camelName}Api.add{detail.Target}(masterId, dto as Create{detail.Target}ItemDto);");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}}} catch {{ failures.push(`Add {EscapeString(detailLabel)}`); }}");
                sb.AppendLine($"{Indent}{Indent}{Indent}}}");
            }
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}\", masterId] }});");
            sb.AppendLine();
            sb.AppendLine($"{Indent}{Indent}{Indent}if (failures.length > 0) {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}toast.warning(`{caption} saved, but ${{failures.length}} detail items failed`);");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}/$id\", params: {{ id: masterId }} }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}}} else {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}toast.success(isEdit ? \"{caption} updated\" : \"{caption} created\");");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}}}");
            sb.AppendLine($"{Indent}{Indent}}} catch {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}toast.error(\"Failed to save {caption}\");");
            sb.AppendLine($"{Indent}{Indent}}} finally {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}setSaving(false);");
            sb.AppendLine($"{Indent}{Indent}}}");
            sb.AppendLine($"{Indent}}}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"{Indent}const createMutation = useMutation({{");
            sb.AppendLine($"{Indent}{Indent}mutationFn: (data: Create{entityName}Dto) => {camelName}Api.create(data),");
            sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} created\");");
            sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}}},");
            sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to create {caption}\"),");
            sb.AppendLine($"{Indent}}});");
            sb.AppendLine();
            sb.AppendLine($"{Indent}const updateMutation = useMutation({{");
            sb.AppendLine($"{Indent}{Indent}mutationFn: (data: Create{entityName}Dto) => {camelName}Api.update(id!, data),");
            sb.AppendLine($"{Indent}{Indent}onSuccess: () => {{");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}s\"] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}queryClient.invalidateQueries({{ queryKey: [\"{camelName}\", id] }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}toast.success(\"{caption} updated\");");
            sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
            sb.AppendLine($"{Indent}{Indent}{Indent}}},");
            sb.AppendLine($"{Indent}{Indent}onError: () => toast.error(\"Failed to update {caption}\"),");
            sb.AppendLine($"{Indent}}});");
            sb.AppendLine();
        }

        sb.AppendLine($"{Indent}useEffect(() => {{");
        sb.AppendLine($"{Indent}{Indent}if (!permissionsLoaded) return;");
        sb.AppendLine($"{Indent}{Indent}if ((!isEdit && !canCreate) || (isEdit && !canUpdate)) {{");
        sb.AppendLine($"{Indent}{Indent}{Indent}toast.error(\"You don't have permission to perform this action\");");
        sb.AppendLine($"{Indent}{Indent}{Indent}navigate({{ to: \"/{kebabPlural}\" }});");
        sb.AppendLine($"{Indent}{Indent}}}");
        sb.AppendLine($"{Indent}}}, [isEdit, canCreate, canUpdate, permissionsLoaded, navigate]);");
        sb.AppendLine();
        sb.AppendLine($"{Indent}if (isEdit && isLoading) return <PageLoading />;");
        sb.AppendLine();

        sb.AppendLine($"{Indent}// eslint-disable-next-line @typescript-eslint/no-explicit-any");
        sb.AppendLine($"{Indent}const ex = existing as any;");
        sb.AppendLine($"{Indent}const defaultValues = isEdit && ex");
        sb.AppendLine($"{Indent}{Indent}? {{");
        foreach (var field in writableFields)
        {
            var camelField = ToCamelCase(field.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelField}: ex.{camelField} ?? {GetDefaultForType(field, entity.Enums)},");
        }
        foreach (var rel in references)
        {
            var camelRelId = ToCamelCase(rel.Name) + "Id";
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelRelId}: ex.{camelRelId} ?? null,");
        }
        sb.AppendLine($"{Indent}{Indent}}}");
        sb.AppendLine($"{Indent}{Indent}: {{");
        foreach (var field in writableFields)
        {
            var camelField = ToCamelCase(field.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelField}: {GetDefaultForType(field, entity.Enums)},");
        }
        foreach (var rel in references)
        {
            var camelRel = ToCamelCase(rel.Name);
            sb.AppendLine($"{Indent}{Indent}{Indent}{camelRel}Id: null,");
        }
        sb.AppendLine($"{Indent}{Indent}}};");
        sb.AppendLine();

        var maxWidth = hasDetails ? "max-w-5xl" : "max-w-2xl";
        sb.AppendLine($"{Indent}return (");
        sb.AppendLine($"{Indent}{Indent}<div className=\"{maxWidth} space-y-4\">");
        sb.AppendLine($"{Indent}{Indent}{Indent}<h1 className=\"text-2xl font-bold\">{{isEdit ? \"Edit\" : \"New\"}} {caption}</h1>");
        sb.AppendLine($"{Indent}{Indent}{Indent}<EntityForm");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}schema={{create{entityName}Schema}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}defaultValues={{defaultValues}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}fields={{fieldConfigs}}");
        if (formLayout is { Count: > 0 })
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}layout={{formLayout}}");

        if (hasDetails)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onSubmit={{handleSubmit}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{saving}}");
        }
        else
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onSubmit={{(data) => isEdit ? updateMutation.mutate(data as Create{entityName}Dto) : createMutation.mutate(data as Create{entityName}Dto)}}");
            sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}loading={{createMutation.isPending || updateMutation.isPending}}");
        }
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}submitLabel={{isEdit ? \"Update\" : \"Create\"}}");
        sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}onCancel={{() => navigate({{ to: \"/{kebabPlural}\" }})}}");

        if (hasDetails)
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}>");
            foreach (var detail in details)
            {
                var camelTarget = ToCamelCase(detail.Target);
                var detailLabel = detail.Label ?? detail.Name;
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}<InlineDetailTable");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}title=\"{EscapeString(detailLabel)}\"");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}items={{{camelTarget}Items}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}onItemsChange={{set{detail.Target}Items}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}columns={{{camelTarget}Columns}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}fieldConfigs={{{camelTarget}FieldConfigs}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}schema={{create{detail.Target}ItemSchema}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}{Indent}defaultValues={{{camelTarget}Defaults}}");
                sb.AppendLine($"{Indent}{Indent}{Indent}{Indent}/>");
            }
            sb.AppendLine($"{Indent}{Indent}{Indent}</EntityForm>");
        }
        else
        {
            sb.AppendLine($"{Indent}{Indent}{Indent}/>");
        }

        sb.AppendLine($"{Indent}{Indent}</div>");
        sb.AppendLine($"{Indent});");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }
}
