// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 14:37:53

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[DefaultProperty(nameof(Name))]
[XafDisplayName("客戶")]
public partial class Customer : BaseObject
{
    public Customer(Session session) : base(session) { }

    private string _code;
    [RuleRequiredField]
    [Size(20)]
    [XafDisplayName("客戶代號")]
    public string Code
    {
        get => _code;
        set => SetPropertyValue(nameof(Code), ref _code, value);
    }

    private string _name;
    [RuleRequiredField]
    [Size(100)]
    [XafDisplayName("客戶姓名")]
    public string Name
    {
        get => _name;
        set => SetPropertyValue(nameof(Name), ref _name, value);
    }

    private string _email;
    [XafDisplayName("電子郵件")]
    public string Email
    {
        get => _email;
        set => SetPropertyValue(nameof(Email), ref _email, value);
    }

    private string _phone;
    [XafDisplayName("電話")]
    public string Phone
    {
        get => _phone;
        set => SetPropertyValue(nameof(Phone), ref _phone, value);
    }

    [Association("Order-Customer")]
    public XPCollection<Order> Orders
    {
        get => GetCollection<Order>(nameof(Orders));
    }

}
