// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 16:14:21

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[XafDisplayName("訂單明細")]
public partial class OrderItem : BaseObject
{
    public OrderItem(Session session) : base(session) { }

    private int _quantity;
    [XafDisplayName("數量")]
    public int Quantity
    {
        get => _quantity;
        set => SetPropertyValue(nameof(Quantity), ref _quantity, value);
    }

    private decimal _price;
    [XafDisplayName("單價")]
    public decimal Price
    {
        get => _price;
        set => SetPropertyValue(nameof(Price), ref _price, value);
    }

    [XafDisplayName("小計")]
    [PersistentAlias("[Quantity] * [Price]")]
    public decimal LineTotal
    {
        get => EvaluateAlias(nameof(LineTotal)) is decimal _v ? _v : 0m;
    }

    private Order _order;
    [XafDisplayName("所屬訂單")]
    [Association("Order-Items")]
    public Order Order
    {
        get => _order;
        set => SetPropertyValue(nameof(Order), ref _order, value);
    }

    private Product _product;
    [RuleRequiredField]
    [XafDisplayName("產品")]
    [Association("OrderItem-Product")]
    public Product Product
    {
        get => _product;
        set => SetPropertyValue(nameof(Product), ref _product, value);
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        Quantity = 1;
        Price = 0m;
    }

}
