// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 14:37:53

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[DefaultProperty(nameof(OrderNo))]
[XafDisplayName("訂單")]
public partial class Order : BaseObject
{
    public Order(Session session) : base(session) { }

    private string _orderNo;
    [RuleRequiredField]
    [Size(20)]
    [XafDisplayName("訂單單號")]
    public string OrderNo
    {
        get => _orderNo;
        set => SetPropertyValue(nameof(OrderNo), ref _orderNo, value);
    }

    private DateTime _orderDate;
    [XafDisplayName("訂單日期")]
    public DateTime OrderDate
    {
        get => _orderDate;
        set => SetPropertyValue(nameof(OrderDate), ref _orderDate, value);
    }

    private decimal _totalAmount;
    [ModelDefault("AllowEdit", "False")]
    [XafDisplayName("總金額")]
    public decimal TotalAmount
    {
        get => _totalAmount;
        set => SetPropertyValue(nameof(TotalAmount), ref _totalAmount, value);
    }

    private Customer _customer;
    [RuleRequiredField]
    [XafDisplayName("客戶")]
    [Association("Order-Customer")]
    public Customer Customer
    {
        get => _customer;
        set => SetPropertyValue(nameof(Customer), ref _customer, value);
    }

    [XafDisplayName("訂單明細")]
    [Association("Order-Items"), DevExpress.Xpo.Aggregated]
    public XPCollection<OrderItem> Items
    {
        get => GetCollection<OrderItem>(nameof(Items));
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        OrderNo = "NEW";
        OrderDate = DateTime.Today;
        TotalAmount = 0m;
    }

}
