// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 14:37:53

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[DefaultProperty(nameof(Name))]
[XafDisplayName("產品")]
public partial class Product : BaseObject
{
    public Product(Session session) : base(session) { }

    private string _code;
    [RuleRequiredField]
    [Size(20)]
    [XafDisplayName("產品編號")]
    public string Code
    {
        get => _code;
        set => SetPropertyValue(nameof(Code), ref _code, value);
    }

    private string _name;
    [RuleRequiredField]
    [Size(100)]
    [XafDisplayName("產品名稱")]
    public string Name
    {
        get => _name;
        set => SetPropertyValue(nameof(Name), ref _name, value);
    }

    private decimal _price;
    [XafDisplayName("定價")]
    public decimal Price
    {
        get => _price;
        set => SetPropertyValue(nameof(Price), ref _price, value);
    }

    private string _description;
    [Size(500)]
    [XafDisplayName("說明")]
    public string Description
    {
        get => _description;
        set => SetPropertyValue(nameof(Description), ref _description, value);
    }

    [Association("OrderItem-Product")]
    public XPCollection<OrderItem> OrderItems
    {
        get => GetCollection<OrderItem>(nameof(OrderItems));
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        Price = 0m;
    }

}
