// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 22:03:33

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[DefaultProperty(nameof(Name))]
[ImageName("BO_Product")]
[XafDisplayName("產品")]
[Description("產品基本資料管理")]
public partial class Product : BaseObject
{
    public Product(Session session) : base(session) { }

    private string _sKU;
    [RuleRequiredField]
    [RuleRegularExpression("SKU_Rule0", DefaultContexts.Save, @"^[A-Z0-9-]{3,20}$", CustomMessageTemplate = "產品編號僅限英數字與連字號")]
    [Size(20)]
    [XafDisplayName("產品編號")]
    public string SKU
    {
        get => _sKU;
        set => SetPropertyValue(nameof(SKU), ref _sKU, value);
    }

    private string _name;
    [RuleRequiredField]
    [Size(100)]
    [XafDisplayName("產品名稱")]
    public string Name
    {
        get => _name;
        set => SetPropertyValue(nameof(Name), ref _name, value);
    }

    private decimal _standardCost;
    [XafDisplayName("標準進價")]
    public decimal StandardCost
    {
        get => _standardCost;
        set => SetPropertyValue(nameof(StandardCost), ref _standardCost, value);
    }

    private int _stockQuantity;
    [XafDisplayName("庫存數量")]
    public int StockQuantity
    {
        get => _stockQuantity;
        set => SetPropertyValue(nameof(StockQuantity), ref _stockQuantity, value);
    }

    [Association("PurchaseOrderItem-Product")]
    public XPCollection<PurchaseOrderItem> PurchaseOrderItems
    {
        get => GetCollection<PurchaseOrderItem>(nameof(PurchaseOrderItems));
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        StandardCost = 0m;
        StockQuantity = 0;
    }

}
