// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 22:03:33

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

public enum PurchaseStatus
{
    [XafDisplayName("草稿")]
    Draft = 0,
    [XafDisplayName("已發出")]
    Issued = 1,
    [XafDisplayName("已收貨")]
    Received = 2,
    [XafDisplayName("已取消")]
    Cancelled = 3
}

[DefaultClassOptions]
[DefaultProperty(nameof(PONumber))]
[ImageName("BO_Order")]
[XafDisplayName("採購單")]
[Description("採購單主檔，負責彙總明細與供應商關聯")]
public partial class PurchaseOrder : BaseObject
{
    public PurchaseOrder(Session session) : base(session) { }

    private string _pONumber;
    [RuleRequiredField]
    [XafDisplayName("採購單號")]
    public string PONumber
    {
        get => _pONumber;
        set => SetPropertyValue(nameof(PONumber), ref _pONumber, value);
    }

    private DateTime _orderDate;
    [RuleRequiredField]
    [XafDisplayName("採購日期")]
    public DateTime OrderDate
    {
        get => _orderDate;
        set => SetPropertyValue(nameof(OrderDate), ref _orderDate, value);
    }

    private PurchaseStatus _status;
    [XafDisplayName("狀態")]
    public PurchaseStatus Status
    {
        get => _status;
        set => SetPropertyValue(nameof(Status), ref _status, value);
    }

    [XafDisplayName("總金額")]
    [PersistentAlias("[Items].Sum([Subtotal])")]
    public decimal TotalAmount
    {
        get => EvaluateAlias(nameof(TotalAmount)) is decimal _v ? _v : 0m;
    }

    private Supplier _supplier;
    [RuleRequiredField]
    [XafDisplayName("供應商")]
    [Association("PurchaseOrder-Supplier")]
    public Supplier Supplier
    {
        get => _supplier;
        set => SetPropertyValue(nameof(Supplier), ref _supplier, value);
    }

    [XafDisplayName("採購明細")]
    [Association("PurchaseOrder-Items"), DevExpress.Xpo.Aggregated]
    public XPCollection<PurchaseOrderItem> Items
    {
        get => GetCollection<PurchaseOrderItem>(nameof(Items));
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        PONumber = "NEW";
        OrderDate = DateTime.Now;
        Status = PurchaseStatus.Draft;
    }

}
