// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 17:40:23

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[XafDisplayName("採購明細")]
[Description("採購單的項目明細，包含數量與單價")]
public partial class PurchaseOrderItem : BaseObject
{
    public PurchaseOrderItem(Session session) : base(session) { }

    private decimal _quantity;
    [RuleRequiredField]
    [XafDisplayName("數量")]
    public decimal Quantity
    {
        get => _quantity;
        set => SetPropertyValue(nameof(Quantity), ref _quantity, value);
    }

    private decimal _unitPrice;
    [RuleRequiredField]
    [XafDisplayName("進貨單價")]
    public decimal UnitPrice
    {
        get => _unitPrice;
        set => SetPropertyValue(nameof(UnitPrice), ref _unitPrice, value);
    }

    [XafDisplayName("小計")]
    [PersistentAlias("[Quantity] * [UnitPrice]")]
    public decimal Subtotal
    {
        get => EvaluateAlias(nameof(Subtotal)) is decimal _v ? _v : 0m;
    }

    private PurchaseOrder _purchaseOrder;
    [XafDisplayName("採購單")]
    [Association("PurchaseOrder-Items")]
    public PurchaseOrder PurchaseOrder
    {
        get => _purchaseOrder;
        set => SetPropertyValue(nameof(PurchaseOrder), ref _purchaseOrder, value);
    }

    private Product _product;
    [RuleRequiredField]
    [XafDisplayName("採購產品")]
    [Association("PurchaseOrderItem-Product")]
    public Product Product
    {
        get => _product;
        set => SetPropertyValue(nameof(Product), ref _product, value);
    }

    public override void AfterConstruction()
    {
        base.AfterConstruction();
        Quantity = 1m;
        UnitPrice = 0m;
    }

}
