// Auto-generated by XekuII.Generator - DO NOT EDIT
// Generated at: 2026-02-06 17:40:23

using System.ComponentModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;

namespace XekuII.ApiHost.BusinessObjects;

[DefaultClassOptions]
[DefaultProperty(nameof(Name))]
[ImageName("BO_Customer")]
[XafDisplayName("供應商")]
[Description("供應商基本資料管理")]
public partial class Supplier : BaseObject
{
    public Supplier(Session session) : base(session) { }

    private string _name;
    [Description("供應商的公司全名")]
    [RuleRequiredField]
    [XafDisplayName("供應商名稱")]
    public string Name
    {
        get => _name;
        set => SetPropertyValue(nameof(Name), ref _name, value);
    }

    private string _contactPerson;
    [XafDisplayName("聯絡人")]
    public string ContactPerson
    {
        get => _contactPerson;
        set => SetPropertyValue(nameof(ContactPerson), ref _contactPerson, value);
    }

    private string _phone;
    [XafDisplayName("聯絡電話")]
    public string Phone
    {
        get => _phone;
        set => SetPropertyValue(nameof(Phone), ref _phone, value);
    }

    private string _address;
    [Size(200)]
    [XafDisplayName("地址")]
    public string Address
    {
        get => _address;
        set => SetPropertyValue(nameof(Address), ref _address, value);
    }

    [Association("PurchaseOrder-Supplier")]
    public XPCollection<PurchaseOrder> PurchaseOrders
    {
        get => GetCollection<PurchaseOrder>(nameof(PurchaseOrders));
    }

}
